<?php
set_time_limit(0);$yr=date("Y",time());
require(__DIR__ . "/../script.inc.php");
					include("../".$config_path."database.default.config.php");
					error_reporting(0);
					$link =mysql_connect($db_server,$db_username,$db_password);
					if(!mysql_select_db($db_name))
					{
					echo '<span style="color:#ff0000;">Database connection failed! Please verify the connection settings in the configuration file</span>
			</td><td>&nbsp;</td></tr><tr height="110px"><td>&nbsp;</td><td valign="top" align="right"></td><td>&nbsp;</td></tr>
			</table>			
			<table width="100%"  height="20px;"  class="bgstylefooter">
			<tr><td align="center">Copyright &copy;'. $yr .'Libescripts.com. All Rights Reserved.</td></tr></table>
			</td><td>&nbsp;</td></tr>
			  <tr  height="25%"><td >&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
			  </tr>
			</table>
			' ;
						exit(0);
					}
					
//include("../config/database.default.config.php");
mysql_query("TRUNCATE TABLE `".$db_tableprefix."nesote_email_settings`");
mysql_query("INSERT INTO `".$db_tableprefix."nesote_email_settings` (`name`, `value`) VALUES
('default_language', '1'),
('themes', '2'),
('emailextension', ''),
('forward_sub_predecessor', 'Fw'),
('reply_sub_predecessor', 'Re'),
('SMTP_host', ''),
('SMTP_port', ''),
('SMTP_username', ''),
('SMTP_password', ''),
('display', '1'),
('engine_name', ''),
('affiliate_id', '1'),
('charset', 'utf-8'),
('adminemail', ''),
('attachment_size', '10'),
('globaladdress_book', '1'),
('user_memory_size', '7000'),
('welcome_email_body', 'welcome to Libe Web Mail.'),
('welcome_email_subject', 'Welcome'),
('common_email_subject', 'Special notice'),
('common_email_body', 'Update with your common mail content'),
('pop3_servername', ''),
('pop3_serveremail', ''),
('pop3_serverpassword', ''),
('catchall_mail', ''),
('automatic_account_creation', ''),
('public_registration', ''),
('alternate_message', 'To view the message, please use an HTML compatible email viewer!'),
('controlpanel', ''),
('controlpanel_version', ''),
('plesk_packetversion', ''),
('plesk_domainid', ''),
('domain_password', ''),
('domain_username', ''),
('domain_name', ''),
('domain_ip', ''),
('forgotpassword_msg', '<br><br>		{msg} {link}'),
('time_difference', ''),
('time_zone', ''),
('time_zone_hour', ''),
('time_zone_mint', ''),
('time_zone_postion', ''),
('memoryusage_publicview', ''),
('memoryusage_publicview_area', ''),
('memorysize_format', '0'),
('restricted_attachment_types', ''),
('public_page_logo', 'banner1.png'),
('user_page_logo', 'banner1.png'),
('mails_per_page', '20'),
('override_themes', '1'),
('admin_timezone', ''),
('imageformats', 'jpg,jpeg,gif,png,bmp'),
('audioformats', ''),
('videoformats', ''),
('rightads_code', ''),
('topads_code', ''),
('adserver_installurl', 'http://www.libedemo.com/libe_adserver_ultimate/'),
('adserver_authenticationcode', 'admin'),
('adserver_topadcount', '1'),
('adserver_rightadcount', '4'),
('publicadstatus', '1'),
('topadtype', '2'),
('rightadtype', '2'),
('min_usernamelength', '6'),
('shortcuts', '0'),
('todolist', '1'),
('min_passwordlength', '2'),
('birthday_email_subject','Happy Birthday'),
('birthday_email_body','<span style=\"color: rgb(102, 0, 153);\">Dear {name},</span><br style=\"color: rgb(102, 0, 153);\"><span style=\"color: rgb(102, 0, 153);\">&nbsp;</span><br style=\"color: rgb(102, 0, 153);\"><span style=\"color: rgb(102, 0, 153);\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><strong style=\"color: rgb(102, 0, 153);\">Wishing</strong><span style=\"color: rgb(102, 0, 153);\"> you great happiness and successes on your </span><strong style=\"color: rgb(102, 0, 153);\">Birthday</strong><br style=\"color: rgb(153, 0, 102);\"><span style=\"color: rgb(153, 0, 102);\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><br style=\"color: rgb(153, 0, 102);\"><span style=\"color: rgb(153, 0, 102);\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br></span>'),
('birthday_mail',1),
('tip_ofthe_day',1),
('portal_status', '0'),
('portal_installation_url', '');
");

mysql_query("TRUNCATE TABLE `".$db_tableprefix."nesote_email_months_messages`");
mysql_query("INSERT INTO `".$db_tableprefix."nesote_email_months_messages` (`month_id`, `lang_id`, `message`) VALUES
(1, 1, 'January'),
(2, 1, 'February'),
(3, 1, 'March'),
(4, 1, 'April'),
(5, 1, 'May'),
(6, 1, 'June'),
(7, 1, 'July'),
(8, 1, 'August'),
(9, 1, 'September'),
(10, 1, 'October'),
(11, 1, 'November'),
(12, 1, 'December'),
(1, 2, 'Enero'),
(2, 2, 'Febrero'),
(3, 2, 'Marzo'),
(4, 2, 'Abril'),
(5, 2, 'Mayo'),
(6, 2, 'Junio'),
(7, 2, 'Julio'),
(8, 2, 'Agosto'),
(9, 2, 'Septiembre'),
(10, 2, 'Octubre'),
(11, 2, 'De noviembre'),
(12, 2, 'Diciembre'),
(1, 3, 'Janvier'),
(2, 3, 'Février'),
(3, 3, 'Mars'),
(4, 3, 'Avril'),
(5, 3, 'Mai'),
(6, 3, 'Juin'),
(7, 3, 'Juillet'),
(8, 3, 'Août'),
(9, 3, 'Septembre'),
(10, 3, 'Octobre'),
(11, 3, 'Novembre'),
(12, 3, 'Décembre');
");
mysql_query("TRUNCATE TABLE `".$db_tableprefix."nesote_email_languages`");
mysql_query("INSERT INTO `".$db_tableprefix."nesote_email_languages` (`language`, `language_script`, `status`, `char_encoding`, `lang_alignment`, `image`,`lang_code`) VALUES
('English', 'English', 1, 'UTF-8', 1, '','eng'),
('Spanish', 'Espanol', 1, 'UTF-8', 1, '','spa'),
('French', 'Français', 1, 'UTF-8', 1, '','fre');
");
mysql_query("TRUNCATE TABLE `".$db_tableprefix."nesote_email_themes`");
mysql_query("INSERT INTO `".$db_tableprefix."nesote_email_themes` (`name`, `style`, `status`, `thumb`) VALUES
('Theme1', 'url(images/themeDemo1.jpg) no-repeat right 0 #0e151d', 1, ''),
('Theme2', 'url(images/themeDemo2.jpg) no-repeat right 0 #5c739d', 1, ''),
('Theme3', 'url(images/themeDemo3.jpg) no-repeat right 0 #120809', 1, ''),
('Theme4', 'url(images/themeDemo4.jpg) no-repeat right 0 #091113', 1, ''),
('Theme5', 'url(images/themeDemo5.jpg) no-repeat right 0 #313131', 1, ''),
('Theme6', 'url(images/themeDemo6.jpg) no-repeat right 0 #124564', 1, ''),
('Theme7', 'url(images/themeDemo7.jpg) no-repeat right 0 #ffc5e9', 1, ''),
('Theme8', 'url(images/themeDemo8.jpg) no-repeat right 0 #030208', 1, ''),
('Theme9', 'url(images/themeDemo9.jpg) no-repeat right 0 #fee0a0', 1, ''),
('Theme10', 'url(images/themeDemo10.jpg) no-repeat right 0 #192511', 1, ''),
('Theme11', 'url(images/themeDemo11.jpg) no-repeat right 0 #cae2a6', 1, ''),
('Theme12', 'url(images/themeDemo12.jpg) no-repeat right 0 #957d5b', 1, ''),
('Theme13', 'url(images/themeDemo13.jpg) no-repeat right 0 #000000', 1, ''),
('Theme14', 'url(images/themeDemo14.jpg) no-repeat right 0 #000000', 1, ''),
('Theme15', 'url(images/themeDemo15.jpg) no-repeat right 0 #3f64b5', 1, ''),
('Theme16', 'url(images/themeDemo16.jpg) no-repeat right 0 #000000', 1, ''),
('Theme17', 'url(images/themeDemo17.jpg) no-repeat right 0 #5b8a22', 1, ''),
('Theme18', 'url(images/themeDemo18.jpg) no-repeat right 0 #091b29', 1, ''),
('Theme19', 'url(images/themeDemo19.jpg) no-repeat right 0 #d2e4e4', 1, ''),
('Theme20', 'url(images/themeDemo20.jpg) no-repeat right 0 #010206', 1, ''),
('Theme21', 'url(images/themeDemo21.jpg) no-repeat right 0 #010206', 1, ''),
('Theme22', 'url(images/themeDemo22.jpg) no-repeat right 0 #0f1901', 1, ''),
('Theme23', 'url(images/themeDemo-repeat.jpg) repeat-x 0 -273px', 1, ''),
('Theme24', 'url(images/themeDemo-repeat.jpg) repeat-x 0 0', 1, ''),
('Theme25', 'url(images/themeDemo-repeat.jpg) repeat-x 0 -544px', 1, ''),
('Theme26', 'url(images/themeDemo-repeat.jpg) repeat-x 0 -681px', 1, ''),
('Theme27', 'url(images/themeDemo-repeat.jpg) repeat-x 0 -818px', 1, ''),
('Theme28', 'url(images/themeDemo-repeat.jpg) repeat-x 0 -137px', 1, ''),
('Theme29', 'url(images/themeDemo-repeat.jpg) repeat-x 0 -955px', 1, ''),
('Theme30', 'url(images/themeDemo-repeat.jpg) repeat-x 0 -1092px', 1, ''),
('Theme31', 'url(images/themeDemo-repeat.jpg) repeat-x 0 -1229px', 1, ''),
('Theme32', 'url(images/themeDemo-repeat.jpg) repeat-x 0 -408px', 1, ''),
('Theme33', 'url(images/themeDemo-repeat.jpg) repeat-x 0 -1366px', 1, ''),
('Theme34', 'url(images/themeDemo-repeat.jpg) repeat-x 0 -1503px', 1, ''),
('Theme35', 'url(images/themeDemo-repeat.jpg) repeat-x 0 -1632px', 1, ''),
('Theme36', 'url(images/themeDemo-repeat.jpg) repeat-x 0 -1769px', 1, ''),
('Theme37', 'url(images/themeDemo2.png) no-repeat right 0 #1f2834', 1, '');
");
mysql_query("TRUNCATE TABLE `".$db_tableprefix."nesote_email_country`");
mysql_query("INSERT INTO `".$db_tableprefix."nesote_email_country` (`code`, `name`) VALUES
('AD', 'Andorra'),
('AE', 'United Arab Emirates'),
('AF', 'Afghanistan'),
('AG', 'Antigua and Barbuda'),
('AI', 'Anguilla'),
('AL', 'Albania'),
('AM', 'Armenia'),
('AN', 'Netherlands Antilles'),
('AO', 'Angola'),
('AQ', 'Antarctica'),
('AR', 'Argentina'),
('AS', 'American Samoa'),
('AT', 'Austria'),
('AU', 'Australia'),
('AW', 'Aruba'),
('AX', 'Aland Islands'),
('AZ', 'Azerbaijan'),
('BA', 'Bosnia and Herzegovina'),
('BB', 'Barbados'),
('BD', 'Bangladesh'),
('BE', 'Belgium'),
('BF', 'Burkina Faso'),
('BG', 'Bulgaria'),
('BH', 'Bahrain'),
('BI', 'Burundi'),
('BJ', 'Benin'),
('BM', 'Bermuda'),
('BN', 'Brunei Darussalam'),
('BO', 'Bolivia'),
('BR', 'Brazil'),
('BS', 'Bahamas'),
('BT', 'Bhutan'),
('BV', 'Bouvet Island'),
('BW', 'Botswana'),
('BY', 'Belarus'),
('BZ', 'Belize'),
('CA', 'Canada'),
('CC', 'Cocos (Keeling) Islands'),
('CD', 'Congo, The Democratic Republic of the'),
('CF', 'Central African Republic'),
('CG', 'Congo'),
('CH', 'Switzerland'),
('CI', 'Cote d\'Ivoire'),
('CK', 'Cook Islands'),
('CL', 'Chile'),
('CM', 'Cameroon'),
('CN', 'China'),
('CO', 'Colombia'),
('CR', 'Costa Rica'),
('CU', 'Cuba'),
('CV', 'Cape Verde'),
('CX', 'Christmas Island'),
('CY', 'Cyprus'),
('CZ', 'Czech Republic'),
('DE', 'Germany'),
('DJ', 'Djibouti'),
('DK', 'Denmark'),
('DM', 'Dominica'),
('DO', 'Dominican Republic'),
('DZ', 'Algeria'),
('EC', 'Ecuador'),
('EE', 'Estonia'),
('EG', 'Egypt'),
('EH', 'Western Sahara'),
('ER', 'Eritrea'),
('ES', 'Spain'),
('ET', 'Ethiopia'),
('EU', 'Europe'),
('FI', 'Finland'),
('FJ', 'Fiji'),
('FK', 'Falkland Islands (Malvinas)'),
('FM', 'Micronesia, Federated States of'),
('FO', 'Faroe Islands'),
('FR', 'France'),
('GA', 'Gabon'),
('GB', 'United Kingdom'),
('GD', 'Grenada'),
('GE', 'Georgia'),
('GF', 'French Guiana'),
('GG', 'Guernsey'),
('GH', 'Ghana'),
('GI', 'Gibraltar'),
('GL', 'Greenland'),
('GM', 'Gambia'),
('GN', 'Guinea'),
('GP', 'Guadeloupe'),
('GQ', 'Equatorial Guinea'),
('GR', 'Greece'),
('GS', 'South Georgia and the South Sandwich Islands'),
('GT', 'Guatemala'),
('GU', 'Guam'),
('GW', 'Guinea-Bissau'),
('GY', 'Guyana'),
('HK', 'Hong Kong'),
('HM', 'Heard Island and McDonald Islands'),
('HN', 'Honduras'),
('HR', 'Croatia'),
('HT', 'Haiti'),
('HU', 'Hungary'),
('ID', 'Indonesia'),
('IE', 'Ireland'),
('IL', 'Israel'),
('IM', 'Isle of Man'),
('IN', 'India'),
('IO', 'British Indian Ocean Territory'),
('IQ', 'Iraq'),
('IR', 'Iran, Islamic Republic of'),
('IS', 'Iceland'),
('IT', 'Italy'),
('JE', 'Jersey'),
('JM', 'Jamaica'),
('JO', 'Jordan'),
('JP', 'Japan'),
('KE', 'Kenya'),
('KG', 'Kyrgyzstan'),
('KH', 'Cambodia'),
('KI', 'Kiribati'),
('KM', 'Comoros'),
('KN', 'Saint Kitts and Nevis'),
('KP', 'Korea, Democratic People\'s Republic of'),
('KR', 'Korea, Republic of'),
('KW', 'Kuwait'),
('KY', 'Cayman Islands'),
('KZ', 'Kazakhstan'),
('LA', 'Lao People\'s Democratic Republic'),
('LB', 'Lebanon'),
('LC', 'Saint Lucia'),
('LI', 'Liechtenstein'),
('LK', 'Sri Lanka'),
('LR', 'Liberia'),
('LS', 'Lesotho'),
('LT', 'Lithuania'),
('LU', 'Luxembourg'),
('LV', 'Latvia'),
('LY', 'Libyan Arab Jamahiriya'),
('MA', 'Morocco'),
('MC', 'Monaco'),
('MD', 'Moldova, Republic of'),
('ME', 'Montenegro'),
('MG', 'Madagascar'),
('MH', 'Marshall Islands'),
('MK', 'Macedonia'),
('ML', 'Mali'),
('MM', 'Myanmar'),
('MN', 'Mongolia'),
('MO', 'Macao'),
('MP', 'Northern Mariana Islands'),
('MQ', 'Martinique'),
('MR', 'Mauritania'),
('MS', 'Montserrat'),
('MT', 'Malta'),
('MU', 'Mauritius'),
('MV', 'Maldives'),
('MW', 'Malawi'),
('MX', 'Mexico'),
('MY', 'Malaysia'),
('MZ', 'Mozambique'),
('NA', 'Namibia'),
('NC', 'New Caledonia'),
('NE', 'Niger'),
('NF', 'Norfolk Island'),
('NG', 'Nigeria'),
('NI', 'Nicaragua'),
('NL', 'Netherlands'),
('NO', 'Norway'),
('NP', 'Nepal'),
('NR', 'Nauru'),
('NU', 'Niue'),
('NZ', 'New Zealand'),
('OM', 'Oman'),
('PA', 'Panama'),
('PE', 'Peru'),
('PF', 'French Polynesia'),
('PG', 'Papua New Guinea'),
('PH', 'Philippines'),
('PK', 'Pakistan'),
('PL', 'Poland'),
('PM', 'Saint Pierre and Miquelon'),
('PN', 'Pitcairn'),
('PR', 'Puerto Rico'),
('PS', 'Palestinian Territory'),
('PT', 'Portugal'),
('PW', 'Palau'),
('PY', 'Paraguay'),
('QA', 'Qatar'),
('RE', 'Reunion'),
('RO', 'Romania'),
('RS', 'Serbia'),
('RU', 'Russian Federation'),
('RW', 'Rwanda'),
('SA', 'Saudi Arabia'),
('SB', 'Solomon Islands'),
('SC', 'Seychelles'),
('SD', 'Sudan'),
('SE', 'Sweden'),
('SG', 'Singapore'),
('SH', 'Saint Helena'),
('SI', 'Slovenia'),
('SJ', 'Svalbard and Jan Mayen'),
('SK', 'Slovakia'),
('SL', 'Sierra Leone'),
('SM', 'San Marino'),
('SN', 'Senegal'),
('SO', 'Somalia'),
('SR', 'Suriname'),
('ST', 'Sao Tome and Principe'),
('SV', 'El Salvador'),
('SY', 'Syrian Arab Republic'),
('SZ', 'Swaziland'),
('TC', 'Turks and Caicos Islands'),
('TD', 'Chad'),
('TF', 'French Southern Territories'),
('TG', 'Togo'),
('TH', 'Thailand'),
('TJ', 'Tajikistan'),
('TK', 'Tokelau'),
('TL', 'Timor-Leste'),
('TM', 'Turkmenistan'),
('TN', 'Tunisia'),
('TO', 'Tonga'),
('TR', 'Turkey'),
('TT', 'Trinidad and Tobago'),
('TV', 'Tuvalu'),
('TW', 'Taiwan'),
('TZ', 'Tanzania, United Republic of'),
('UA', 'Ukraine'),
('UG', 'Uganda'),
('UM', 'United States Minor Outlying Islands'),
('US', 'United States'),
('UY', 'Uruguay'),
('UZ', 'Uzbekistan'),
('VA', 'Holy See (Vatican City State)'),
('VC', 'Saint Vincent and the Grenadines'),
('VE', 'Venezuela'),
('VG', 'Virgin Islands, British'),
('VI', 'Virgin Islands, U.S.'),
('VN', 'Vietnam'),
('VU', 'Vanuatu'),
('WF', 'Wallis and Futuna'),
('WS', 'Samoa'),
('YE', 'Yemen'),
('YT', 'Mayotte'),
('ZA', 'South Africa'),
('ZM', 'Zambia'),
('ZW', 'Zimbabwe');

");
mysql_query("TRUNCATE TABLE `".$db_tableprefix."nesote_email_messages`");
mysql_query("INSERT INTO `".$db_tableprefix."nesote_email_messages` (`msg_id`, `lang_id`, `wordscript`) VALUES
(1, 1, 'Mail'),
(2, 1, 'Contacts'),
(3, 1, 'Calendar'),
(4, 1, 'Settings'),
(5, 1, 'Home'),
(6, 1, 'Username'),
(7, 1, 'Password'),
(8, 1, 'Signup'),
(9, 1, 'Login'),
(10, 1, 'New Mail'),
(11, 1, 'Get Mail'),
(12, 1, 'Spam'),
(13, 1, 'Move to'),
(14, 1, 'Delete'),
(15, 1, 'Reply'),
(16, 1, 'Reply All'),
(17, 1, 'Forward'),
(18, 1, 'More Actions'),
(19, 1, 'Inbox'),
(20, 1, 'Draft'),
(21, 1, 'Sent'),
(22, 1, 'Trash'),
(23, 1, 'Personal'),
(24, 1, 'New Contact'),
(25, 1, 'New group'),
(26, 1, 'Edit'),
(27, 1, 'Import'),
(28, 1, 'Export'),
(29, 1, 'Sync'),
(30, 1, 'No mails to display'),
(31, 1, 'To'),
(32, 1, 'Cc'),
(33, 1, 'Bcc'),
(34, 1, 'Subject'),
(35, 1, 'Attachments'),
(36, 1, 'Save to drafts'),
(37, 1, 'Send'),
(38, 1, 'Message'),
(39, 1, 'Logout'),
(40, 1, 'First Name'),
(41, 1, 'Last Name'),
(42, 1, 'Email'),
(43, 1, 'Date of Birth'),
(44, 1, 'Title'),
(45, 1, 'Company'),
(46, 1, 'Phone'),
(47, 1, 'Address'),
(48, 1, 'Website'),
(49, 1, 'Group'),
(50, 1, 'Add'),
(51, 1, 'No subject'),
(52, 1, 'On'),
(53, 1, 'Sub'),
(54, 1, 'From'),
(55, 1, 'days ago'),
(56, 1, 'hours ago'),
(57, 1, 'minutes ago'),
(58, 1, 'seconds ago'),
(59, 1, 'Discard'),
(60, 1, 'Attach More Files'),
(61, 1, 'All'),
(62, 1, 'mm/dd/yyyy'),
(63, 1, 'Save Contacts'),
(64, 1, 'Groups'),
(65, 1, 'ss'),
(66, 1, 'No contacts in this folder.'),
(67, 1, 'No contacts details in this folder.'),
(68, 1, 'Webmail'),
(69, 1, 'Calender'),
(70, 1, 'Spam'),
(71, 1, 'Filters'),
(72, 1, 'Options'),
(73, 1, 'Password'),
(74, 1, 'Mark as read'),
(75, 1, 'Mark as unread'),
(76, 1, 'This is your email account login name.'),
(77, 1, '2 Pane'),
(78, 1, '3 Pane'),
(79, 1, 'Save Settings'),
(80, 1, 'Delete Selected'),
(81, 1, 'No emails are  currently filtered.'),
(82, 1, 'Specify which folder the rule will deliver to'),
(83, 1, 'Add star'),
(84, 1, 'Remove star'),
(85, 1, 'Select All'),
(86, 1, 'Deselect All'),
(87, 1, 'New Rule'),
(88, 1, 'Body'),
(89, 1, 'Exact Match'),
(90, 1, 'Starts With'),
(91, 1, 'Ends With'),
(92, 1, 'Contains'),
(93, 1, 'And'),
(94, 1, 'Filter Rule'),
(95, 1, 'Action'),
(96, 1, '{rule_from} {from_match} \'{from_value}\' {end1} {rule_subject} {subject_match} \'{subject_value}\' {end2}{rule_body} {body_match} \'{body_value}\''),
(97, 1, 'Specify a list of email addresses,domain name in your whitelist,each one must be seperated by a comma. Any email that matches will automatically be marked as trusted without being classified as Spam.'),
(98, 1, 'Specify a list of email addresses,domain name in your blacklist,each one must be seperated by a comma. Any email that matches will automatically be marked as Spam.'),
(99, 1, 'Edit Rule'),
(100, 1, 'EditRule'),
(101, 1, 'Download'),
(102, 1, 'View Image'),
(103, 1, 'Username cannot be left blank.'),
(104, 1, 'Password cannot be left blank.'),
(105, 1, 'Desired Login Name'),
(106, 1, 'Create My Account'),
(107, 1, 'Check Availability'),
(108, 1, 'Sorry, your login name can\'t be exceed 32 characters.'),
(109, 1, 'Sorry, your login name must be between {min_usernamelength} and 32 characters long.'),
(110, 1, '{mailid} is available.'),
(111, 1, '{mailid} is not available.'),
(112, 1, 'First name cannot be left blank.'),
(113, 1, 'Last name cannot be left blank.'),
(114, 1, 'Desired Login Name cannot be left blank.'),
(115, 1, 'Current Password'),
(116, 1, 'New Password'),
(117, 1, 'Confirm Password'),
(118, 1, 'Confirm Password cannot be left blank.'),
(119, 1, 'New Password cannot be left blank.'),
(120, 1, 'Security Question'),
(121, 1, 'Answer'),
(122, 1, 'Gender'),
(123, 1, 'Country'),
(124, 1, 'Invalid login name'),
(125, 1, 'Security Question cannot be left blank.'),
(126, 1, 'Answer cannot be left blank.'),
(127, 1, 'Gender field cannot be left blank.'),
(128, 1, 'Please select the day field.'),
(129, 1, 'Please select the month field.'),
(130, 1, 'Please select the year field.'),
(131, 1, 'Please select a country.'),
(132, 1, 'Passwords do not match.'),
(133, 1, 'Day'),
(134, 1, 'Month'),
(135, 1, 'Year'),
(136, 1, 'Select One'),
(137, 1, 'Male'),
(138, 1, 'Female'),
(139, 1, 'Select a country'),
(140, 1, 'Choose a question........'),
(141, 1, 'What is the first name of your best childhood friend?'),
(142, 1, 'What was the name of your primary school?'),
(143, 1, 'What is the name of the first company you worked for?'),
(144, 1, 'What is your pet name?'),
(145, 1, 'What was your first phone number?'),
(146, 1, 'Write my own question'),
(147, 1, 'Word Verification'),
(148, 1, 'Image varification failed.Please try again.'),
(149, 1, 'Word verification cannot be left blank.'),
(150, 1, 'Already a member'),
(151, 1, 'Whitelist Senders'),
(152, 1, 'Blacklist Senders'),
(153, 1, 'Enable Forward'),
(154, 1, 'Forward Mail'),
(155, 1, 'Enable Autoreply'),
(156, 1, 'Autoreply message'),
(157, 1, 'Off'),
(158, 1, 'Please Enter the Email ID.'),
(159, 1, 'Invalid E-mail ID.'),
(160, 1, 'Autoreply message cannot be left blank.'),
(161, 1, 'Suceessfully Saved Your Settings.'),
(162, 1, 'Please select the settings option.'),
(163, 1, 'Search results for {search} in {folder}'),
(164, 1, 'All Folders'),
(165, 1, 'Please select the folder.'),
(166, 1, 'Rule allready exist.'),
(167, 1, 'Account Name'),
(168, 1, 'Default View'),
(169, 1, 'Language'),
(170, 1, 'Themes'),
(171, 1, 'Signature'),
(172, 1, 'Please select a contact.'),
(173, 1, 'Message has been sent'),
(174, 1, '1 conversation has been moved to trash'),
(175, 1, '1 conversation has been moved from {fromfolder} to {tofolder}'),
(176, 1, 'Deselect'),
(177, 1, '{number} conversations have been moved to trash'),
(178, 1, '{number} conversations have been moved from {fromfolder} to {tofolder}'),
(179, 1, 'Edit Contact'),
(180, 1, 'Edit Group'),
(181, 1, '{number} conversations have been deleted permenantly'),
(182, 1, '1 conversation has been deleted permenantly'),
(183, 1, '1 conversation has been marked as read'),
(184, 1, '{number} conversations have been marked as read'),
(185, 1, '1 conversation has been starred'),
(186, 1, '{number} conversations have been starred'),
(187, 1, '1 conversation has been marked as unread'),
(188, 1, '{number} conversations have been marked as unread'),
(189, 1, '1 conversation has been unstarred'),
(190, 1, '{number} conversations have been unstarred'),
(191, 1, '1 conversation has been marked as spam'),
(192, 1, '{number} conversations have been marked as spam'),
(193, 1, 'Domain {domain} exist in both whitelist and black list!Please remove it.'),
(194, 1, 'Email address {email} exist in both whitelist and black list!Please remove it.'),
(195, 1, 'The settings have been successfully updated.'),
(196, 1, 'Please fill up atleast one field.'),
(197, 1, 'Are you sure want to delete'),
(198, 1, 'Succesfully added a new contact.'),
(199, 1, '{number} contact has been deleted.'),
(200, 1, 'Invalid login! Username or password is incorrect.'),
(201, 1, 'Add Cc'),
(202, 1, 'Add Bcc'),
(203, 1, 'Existing Groups'),
(204, 1, 'This action will result in loss of data for permanently.Do you want to continue?'),
(205, 1, 'Starred'),
(206, 1, 'Delete Contact'),
(207, 1, 'Your mail has been saved to drafts'),
(208, 1, 'Search Results for \'{searchvalue}\' in \'{group}\''),
(209, 1, 'My Contacts'),
(210, 1, 'All Groups'),
(211, 1, 'Other Contacts'),
(212, 1, 'Global Contacts'),
(213, 1, 'Rename'),
(214, 1, 'Group has been renamed to {groupname}.'),
(215, 1, 'Group {groupname} has been created.'),
(216, 1, 'Images are not displayed'),
(217, 1, 'Display images below'),
(218, 1, 'Always display images from '),
(223, 1, 'The contact has been added.'),
(219, 1, 'Group has successfully been deleted.'),
(220, 1, 'Folder has been renamed to {foldername}.'),
(221, 1, 'Folder {foldername} has been created.'),
(222, 1, 'Folder has successfully been deleted.'),
(224, 1, 'Email cannot be left blank.'),
(225, 1, 'Please enter a valid email.'),
(226, 1, 'Please enter a valid phone number.'),
(227, 1, 'Contact information has been saved.'),
(228, 1, 'Contacts already exist.'),
(229, 1, 'Already registered.Choose another username.'),
(230, 1, 'Group {groupname} already exist.Please choose another name.'),
(231, 1, 'Please select the time zone.'),
(232, 1, 'Time Zone'),
(233, 1, 'Select the time zone'),
(234, 1, 'Attachment file format not supported'),
(235, 1, 'Sorry, your password can\'t be exceed 32 characters.'),
(236, 1, 'Sorry, your password must be between 6 and 32 characters long.'),
(237, 1, 'Sorry, your confirm password must be between 6 and 32 characters long.'),
(238, 1, 'Sorry, your confirm password can\'t be exceed 32 characters.'),
(239, 1, 'Filter rule successfully deleted.'),
(240, 1, 'You want to delete this filter rule. Press OK to continue.'),
(241, 1, 'All Fields are empty!!!'),
(242, 1, 'Please enter the  current password!!!'),
(243, 1, 'Please enter the new  password!!!'),
(244, 1, 'Please enter the  confirm password!!!'),
(245, 1, 'Current password is wrong!!!'),
(246, 1, 'New password and Confirm passwords are different!!'),
(247, 1, 'Whitelist senders contains repeated domain name list.Please remove it!!!'),
(248, 1, 'Whitelist senders contain repeated emails list.Please remove it!!!'),
(249, 1, 'Blacklist senders contain repeated email list.Please remove it!!!'),
(250, 1, 'Blacklist senders contain repeated domain name list.Please remove it!!!'),
(251, 1, 'Your domain extension {extension} is not correct'),
(252, 1, 'Domain name should not begin and end with \'-\''),
(253, 1, 'Your domain name should not have special characters'),
(254, 1, 'Your Domain name is too short or long'),
(255, 1, 'Whitelist senders contain invalid mail address.'),
(256, 1, 'Blacklist senders contain invalid mail address.'),
(257, 1, 'Please insert either Whitelist or Blacklist senders details.'),
(258, 1, 'Email id repeated.Please Remove it!!!'),
(259, 1, 'Autoreply subject cannot be left blank.'),
(260, 1, 'Please enter the forward email id.'),
(261, 1, 'Please enter the auto reply message.'),
(262, 1, 'Please enter the auto reply subject.'),
(263, 1, 'Forgot Password?'),
(264, 1, 'Forgot your password?'),
(265, 1, 'Create A new Account'),
(266, 1, 'Libe Web Mail'),
(267, 1, 'Cancel'),
(268, 1, 'Continue'),
(269, 1, 'Forgot Your Password'),
(270, 1, 'Please enter your username.'),
(271, 1, 'Invalid User'),
(272, 1, 'Alternate Email'),
(273, 1, 'Answer the question'),
(274, 1, 'Your question'),
(275, 1, 'OR'),
(276, 1, 'Submit'),
(277, 1, 'Please enter the answer.'),
(278, 1, 'Your new password is'),
(279, 1, 'Please login now with your new password.'),
(280, 1, 'Invalid user details'),
(281, 1, 'Date'),
(282, 1, 'Show details'),
(283, 1, 'Hide details'),
(284, 1, 'me'),
(285, 1, 'Sorry,password can\'t be changed please inform to the administrator.'),
(286, 1, 'Passwod Recovery'),
(287, 1, 'If you want to change your password,'),
(288, 1, 'Click here'),
(289, 1, 'Please enter the password!!!'),
(290, 1, 'Password strength is weak.Choose another one.'),
(291, 1, 'Very Weak'),
(292, 1, 'Weak'),
(293, 1, 'Good'),
(294, 1, 'Strong'),
(295, 1, 'Very Strong'),
(296, 1, 'Password strength'),
(297, 1, 'Password not entered'),
(298, 1, 'Please enter the alternate email id at the time of your registration you entered.'),
(299, 1, 'Please enter the new alternate email id.'),
(300, 1, 'Please check your alternate email and continue the password recovery process'),
(301, 1, 'OK'),
(302, 1, 'To get a new password'),
(6, 2, 'Nombre de usuario'),
(7, 2, 'Contraseña'),
(8, 2, 'Inscripción'),
(9, 2, 'Login'),
(263, 2, '¿Has olvidado tu contraseña?'),
(266, 2, 'Libe Web Mail'),
(6, 3, 'Nom d\'utilisateur'),
(7, 3, 'Mot de passe'),
(8, 3, 'S\'inscrire'),
(9, 3, 'Login'),
(263, 3, 'Mot de passe oublié?'),
(1, 2, 'Correo'),
(2, 2, 'Contactos'),
(3, 2, 'Calendario'),
(4, 2, 'Configuración'),
(5, 2, 'Casa'),
(10, 2, 'Correo nuevo'),
(11, 2, 'Recibir mensajes'),
(12, 2, 'Spam'),
(13, 2, 'Mover a'),
(14, 2, 'Borrar'),
(15, 2, 'Respuesta'),
(16, 2, 'Responder a todos'),
(17, 2, 'Adelante'),
(18, 2, 'Más acciones'),
(19, 2, 'Bandeja de entrada'),
(20, 2, 'Borrador'),
(21, 2, 'Enviados'),
(22, 2, 'Basura'),
(23, 2, 'Personal'),
(24, 2, 'De contacto'),
(25, 2, 'Grupo nuevo'),
(26, 2, 'Editar'),
(27, 2, 'Importación'),
(28, 2, 'Exportación'),
(29, 2, 'Sync'),
(30, 2, 'No hay mensajes para mostrar'),
(31, 2, 'Para'),
(32, 2, 'CC'),
(33, 2, 'CCO'),
(34, 2, 'Tema'),
(35, 2, 'Adjuntos'),
(36, 2, 'Guardar en borradores'),
(37, 2, 'Enviar'),
(38, 2, 'Mensaje'),
(39, 2, 'Desconectarse'),
(40, 2, 'Nombre'),
(41, 2, 'Apellido'),
(42, 2, 'Correo electrónico'),
(43, 2, 'Fecha de Nacimiento'),
(44, 2, 'Título'),
(45, 2, 'Empresa'),
(46, 2, 'Teléfono'),
(47, 2, 'Dirección'),
(48, 2, 'Sitio web'),
(49, 2, 'Grupo'),
(51, 2, 'No hay tema'),
(52, 2, 'En'),
(53, 2, 'Sub'),
(54, 2, 'De'),
(55, 2, 'Hace días'),
(56, 2, 'Hace horas'),
(57, 2, 'Hace minutos'),
(58, 2, 'Hace segundos'),
(59, 2, 'Descartar'),
(60, 2, 'Adjuntar más archivos'),
(61, 2, 'Todos'),
(62, 2, 'mm / dd / aaaa'),
(63, 2, 'Guardar Contactos'),
(64, 2, 'Grupos'),
(65, 2, 'ss'),
(66, 2, 'No hay contactos en esta carpeta.'),
(67, 2, 'No contacts details in this folder.'),
(68, 2, 'Webmail'),
(71, 2, 'Filtros'),
(72, 2, 'Opciones'),
(73, 2, 'Contraseña'),
(74, 2, 'Marcar como leído'),
(75, 2, 'Marcar como no leído'),
(76, 2, 'Esta es su cuenta de correo electrónico nombre de usuario.'),
(50, 2, 'Añadir'),
(69, 2, 'Configuración del calendario'),
(70, 2, 'Spam'),
(77, 2, 'Panel 2'),
(78, 2, 'Panel 3'),
(79, 2, 'Guardar configuración'),
(80, 2, 'Eliminar seleccionados'),
(81, 2, 'No hay mensajes de correo electrónico están filtrados.'),
(82, 2, 'Especifique en qu'),
(83, 2, 'Añadir estrella'),
(84, 2, 'Eliminar estrella'),
(85, 2, 'Seleccionar todos'),
(86, 2, 'Deseleccionar todos'),
(87, 2, 'Nueva regla'),
(88, 2, 'Cuerpo'),
(89, 2, 'Concordancia exacta'),
(90, 2, 'Comienza con la'),
(91, 2, 'Termina con'),
(92, 2, 'Contiene'),
(93, 2, 'Y'),
(94, 2, 'La regla del filtro'),
(95, 2, 'Acción'),
(96, 2, '{rule_from} {from_match} \'{from_value}\' {end1} {rule_subject} {subject_match} \'{subject_value}\' {end2}{rule_body} {body_match} \'{body_value}\''),
(97, 2, 'Especifica una lista de direcciones de correo electrónico, nombre de dominio en su lista blanca, cada uno debe estar separado por una coma. Cualquier correo electrónico que los partidos serán automáticamente marcados como de confianza sin ser clasificados como Spam.'),
(99, 2, 'Editar regla'),
(100, 2, 'EditRule'),
(101, 2, 'Descargar'),
(102, 2, 'Ver imagen'),
(103, 2, 'Nombre de usuario no puede dejarse en blanco.'),
(104, 2, 'Password cannot be left blank.'),
(105, 2, 'Nombre de acceso deseado'),
(106, 2, 'Crear Mi Cuenta'),
(107, 2, 'Obtener la disponibilidad'),
(108, 2, 'Lo sentimos, su nombre de usuario no puede superar los 32 caracteres.'),
(109, 2, 'Lo sentimos, su nombre de usuario debe tener entre {min_usernamelength} y 32 caracteres.'),
(110, 2, '{mailid} está disponible.'),
(111, 2, '{mailid} no está disponible.'),
(112, 2, 'Nombre no puede dejarse en blanco.'),
(113, 2, 'Apellido no puede dejarse en blanco.'),
(114, 2, 'Nombre de acceso deseado no puede dejarse en blanco.'),
(116, 2, 'Nueva Contraseña'),
(117, 2, 'Confirmar contraseña'),
(119, 2, 'Una nueva contraseña no puede dejarse en blanco.'),
(120, 2, 'Pregunta de seguridad'),
(122, 2, 'Género'),
(123, 2, 'País'),
(124, 2, 'Nombre de usuario no válido'),
(125, 2, 'Pregunta de seguridad no puede dejarse en blanco.'),
(126, 2, 'Respuesta no puede dejarse en blanco.'),
(127, 2, 'campo de género no puede dejarse en blanco.'),
(128, 2, 'Por favor, seleccione el campo al día.'),
(129, 2, 'Por favor, seleccione el campo de mes.'),
(130, 2, 'Por favor, seleccione el campo de año.'),
(131, 2, 'Por favor seleccione un país.'),
(132, 2, 'Las contraseñas no coinciden.'),
(133, 2, 'Día'),
(134, 2, 'Mes'),
(136, 2, 'Seleccione Uno'),
(137, 2, 'Masculino'),
(138, 2, 'Femenino'),
(139, 2, 'Seleccione un país'),
(140, 2, 'Elija una pregunta ........'),
(141, 2, '¿Cuál es el nombre de su amigo de la infancia?'),
(146, 2, 'Escribir mi propia pregunta'),
(147, 2, 'Verificación de la palabra'),
(148, 2, 'varification imagen fracasado. Por favor, inténtelo de nuevo.'),
(150, 2, 'Ya eres un miembro'),
(151, 2, 'Lista blanca de remitentes'),
(152, 2, 'Lista negra de remitentes'),
(153, 2, 'Habilitar Adelante'),
(154, 2, 'Reenviar Correo'),
(155, 2, 'Habilitar Respuesta automática'),
(156, 2, 'Respuesta automática a las páginas de'),
(158, 2, 'Por favor introduce el correo electrónico de identificación.'),
(159, 2, 'E-mail válido de identificación.'),
(161, 2, 'Suceessfully guardado las opciones.'),
(162, 2, 'Seleccione la opción de configuración.'),
(163, 2, 'Resultados de búsqueda para {search} en {folder}'),
(164, 2, 'Todas las carpetas'),
(165, 2, 'Por favor, seleccione la carpeta.'),
(166, 2, 'Regla allready existe.'),
(167, 2, 'Nombre de la cuenta'),
(168, 2, 'Archivo:'),
(169, 2, 'Idioma'),
(170, 2, 'Temas'),
(171, 2, 'Firma'),
(172, 2, 'Por favor, seleccione un contacto.'),
(173, 2, 'El mensaje ha sido enviado'),
(174, 2, '1 conversación se ha movido a la papelera'),
(175, 2, '1 conversación se ha pasado de ser {fromfolder} a {tofolder}'),
(176, 2, 'Suprimir selección'),
(177, 2, '{number} conversaciones se han movido a la papelera'),
(179, 2, 'Modificar contacto'),
(180, 2, 'Editar grupo'),
(193, 2, 'Dominio {domain} existen tanto en la lista blanca y la lista de negro! Por favor, elimínela.'),
(195, 2, 'Los ajustes se han actualizado correctamente.'),
(196, 2, 'Rellene al menos un campo.'),
(197, 2, '¿Estás seguro que quieres eliminar'),
(198, 2, 'Ha agregado un nuevo contacto.'),
(200, 2, 'Entrada no válido! Nombre de usuario o contraseña es incorrecta.'),
(201, 2, 'Añadir Cc'),
(202, 2, 'Añadir CCO'),
(203, 2, 'Los grupos existentes\r\n'),
(204, 2, 'Esta acción resultará en la pérdida de datos para permanently.Do desea continuar?'),
(205, 2, 'Favoritas'),
(206, 2, 'Eliminar contacto'),
(207, 2, 'Tu correo electrónico se ha guardado en los borradores'),
(208, 2, 'Resultados de la búsqueda para \'{searchvalue}\' en \'{group}\''),
(115, 2, 'Contraseña actual'),
(118, 2, 'Confirmar contraseña no puede dejarse en blanco.'),
(303, 1, 'The group name is too long. Please try another name'),
(304, 1, 'No conversation has been selected'),
(305, 1, '{number} contact has been added to group {groupname}'),
(306, 1, '{number} contact has been removed from group {groupname}.'),
(307, 1, 'Keyword cannot be null!'),
(308, 1, 'Register Now'),
(309, 1, 'Sign In'),
(310, 1, 'Add to'),
(311, 1, 'Remove from'),
(312, 1, 'You have Successfully Registered.'),
(319, 1, 'Attachment size exceeds!'),
(320, 1, 'Invalid Username'),
(314, 1, 'Phone number cannot be null.'),
(315, 1, 'View group {foldername} contacts.'),
(13, 3, 'Passer à'),
(12, 3, 'Spam'),
(11, 3, 'Get Mail'),
(10, 3, 'Nouveau message'),
(5, 3, 'Maison'),
(4, 3, 'Paramètres'),
(3, 3, 'Calendrier'),
(2, 3, 'Contacts'),
(1, 3, 'Courrier'),
(313, 1, 'You are currently using {memoryused} MB.'),
(314, 1, 'Phone number cannot be null.'),
(315, 1, 'View group {foldername} contacts.'),
(316, 1, 'Memory Usage'),
(317, 1, 'The folder name you have chosen already exists. Please try another name.'),
(318, 1, 'You are currently using {percent}% of your {totalmemory} MB.'),
(321, 1, 'Password Recovery'),
(322, 1, 'Verify Your Identity'),
(323, 1, 'Search Mail'),
(324, 1, 'Search Contact'),
(325, 1, 'You must give a name to the group.'),
(326, 1, 'Desired login name contains invalid characters'),
(327, 1, 'Desired login name contains invalid characters.Please choose another loginname'),
(328, 1, 'Languages'),
(329, 1, 'Default'),
(330, 1, 'Please specify at least one recipient.'),
(331, 1, 'Send message without a subject?'),
(332, 1, 'Send this message without text in the body?'),
(333, 1, 'Page Loading'),
(334, 1, 'Desired Login Name contains invalid characters.'),
(335, 1, 'Desired Login Name must begin with a letter.'),
(336, 1, '1 Pane'),
(337, 1, 'Mails Per Page'),
(338, 1, 'Please select any filter rule'),
(339, 1, 'Autoforward facility is available only with domain extension \'@valiyapalli.com\' in demo version'),
(340, 1, 'This operation is not allowed in demo version.'),
(339, 2, 'autoforward instalación sólo está disponible con la extensión de dominio \'@valiyapalli.com\' en la versión demo'),
(98, 2, 'Especifica una lista de direcciones de correo electrónico, nombre de dominio en su lista negra, cada uno debe estar separado por una coma. Cualquier correo electrónico que coincide automáticamente será marcado como spam.'),
(135, 2, 'Año'),
(142, 2, '¿Cuál era el nombre de su escuela primaria?'),
(143, 2, '¿Cuál es el nombre de la primera empresa que trabajó?'),
(144, 2, '¿Cuál es su nombre de su mascota?'),
(145, 2, '¿Cuál fue su primer número de teléfono?'),
(149, 2, 'verificación de la palabra no puede dejarse en blanco.'),
(160, 2, 'Respuesta automática a las páginas no se puede dejar en blanco.'),
(178, 2, '{number} las conversaciones se han pasado de ser {fromfolder} a {tofolder}'),
(181, 2, '{number} las conversaciones se han suprimido permenantly'),
(182, 2, '1 conversación se ha eliminado permenantly'),
(183, 2, '1 conversación se ha marcado como leído'),
(184, 2, '{number} las conversaciones se han marcado como leído'),
(185, 2, '1 conversación se ha destacado'),
(186, 2, '{number} conversaciones se han destacado'),
(187, 2, '1 conversación se ha marcado como no leído'),
(188, 2, '{number} las conversaciones se han marcado como no leído'),
(189, 2, '1 conversación se ha eliminado la estrella'),
(190, 2, '{number} las conversaciones se han eliminado la estrella'),
(191, 2, '1 conversación se ha marcado como spam'),
(192, 2, '{number} conversaciones se han marcado como spam'),
(194, 2, 'Dirección de correo electrónico {email} existen tanto en la lista blanca y la lista de negro! Por favor, retírelo.'),
(199, 2, '{number} contacto se ha eliminado.'),
(209, 2, 'Mis contactos'),
(210, 2, 'Todos los grupos'),
(211, 2, 'Otros contactos'),
(212, 2, 'Contactos Globales'),
(213, 2, 'Cambiar el nombre de'),
(214, 2, 'Grupo se ha cambiado a {groupname}.'),
(215, 2, 'Grupo [groupname} se ha creado.'),
(216, 2, 'Las imágenes no se muestran'),
(217, 2, 'Mostrar las imágenes a continuación'),
(218, 2, 'Mostrar siempre imágenes de'),
(223, 2, 'El contacto se ha añadido.'),
(219, 2, 'Grupo ha sido borrado con éxito.'),
(220, 2, 'Folder se ha cambiado a {foldername}.'),
(221, 2, 'Carpeta {foldername} se ha creado.'),
(222, 2, 'Folder ha sido borrado con éxito.'),
(224, 2, 'El correo electrónico no puede dejarse en blanco.'),
(225, 2, 'Por favor ingrese un correo electrónico válida.'),
(226, 2, 'Por favor, introduzca un número de teléfono válido.'),
(227, 2, 'La información de contacto se ha guardado.'),
(228, 2, 'Contactos ya existen.'),
(229, 2, 'Ya se registró. Elija otro nombre de usuario.'),
(230, 2, 'Grupo {groupname} ya existen. Por favor, elija otro nombre.'),
(231, 2, 'Por favor, seleccione la zona horaria.'),
(232, 2, 'Zona horaria'),
(233, 2, 'Seleccione la zona horaria'),
(234, 2, 'Adjunto archivo de formato no soportado'),
(235, 2, 'Lo sentimos, tu contraseña no puede ser superior a 32 caracteres.'),
(236, 2, 'Lo sentimos, tu contraseña debe tener entre 6 y 32 caracteres.'),
(237, 2, 'Lo sentimos, tu confirma la contraseña debe tener entre 6 y 32 caracteres.'),
(238, 2, 'Lo sentimos, tu confirma la contraseña no puede ser superior a 32 caracteres.'),
(239, 2, 'regla de filtrado se han eliminado correctamente.'),
(240, 2, 'Usted desea eliminar esta regla de filtrado. Pulse Aceptar para continuar.'),
(241, 2, 'Todos los campos están vacíos!'),
(242, 2, 'Por favor, introduzca la contraseña actual!'),
(243, 2, 'Por favor, introduzca la nueva contraseña!'),
(244, 2, 'Por favor introduce el confirmar la contraseña!'),
(245, 2, 'La contraseña actual es incorrecto!'),
(246, 2, 'Nueva contraseña y Confirmar contraseñas son diferentes!'),
(247, 2, 'Lista blanca de remitentes de dominio contiene repetidas lista de nombres. Por favor, quite!'),
(248, 2, 'Lista blanca de remitentes contienen mensajes de correo electrónico repetidos lista. Por favor, quite!'),
(249, 2, 'Lista negra de remitentes de correo electrónico contienen repetidas lista. Por favor, quite!'),
(250, 2, 'Lista negra de remitentes de dominio contienen repetidas lista de nombres. Por favor, quite!'),
(251, 2, 'Su dominio de extensión {extension} no es correcto'),
(252, 2, 'Nombre de dominio no se debe comenzar con el final \'-\''),
(253, 2, 'Su nombre de dominio no deben tener caracteres especiales'),
(254, 2, 'Su nombre de dominio es demasiado corto o largo'),
(255, 2, 'Lista blanca de remitentes contienen la dirección de correo válida.'),
(256, 2, 'Lista negra de remitentes contienen la dirección de correo válida.'),
(257, 2, 'Por favor, introduzca ya sea blanca o lista negra de remitentes detalles.'),
(258, 2, 'Identificación del email repetirse. Por favor, quitar!'),
(259, 2, 'Respuesta automática a sujeto no puede dejarse en blanco.'),
(260, 2, 'Por favor introduce el correo electrónico hacia adelante id.'),
(261, 2, 'Por favor introduce el mensaje de respuesta automática.'),
(262, 2, 'Por favor introduce el tema de auto respuesta.'),
(264, 2, '¿Olvidaste tu contraseña?'),
(265, 2, 'Crear una cuenta nueva'),
(267, 2, 'Cancelar'),
(268, 2, 'Continuar'),
(269, 2, '¿Olvidó su contraseña'),
(270, 2, 'Por favor ingrese su nombre de usuario.'),
(271, 2, 'Usuario no válido'),
(272, 2, 'Correo electrónico alternativo'),
(273, 2, 'Responde a la pregunta'),
(274, 2, 'Su pregunta'),
(275, 2, 'O'),
(276, 2, 'Presentar'),
(277, 2, 'Por favor, introduzca la respuesta.'),
(278, 2, 'Su nueva contraseña es'),
(279, 2, 'Por favor, iniciar sesión ahora con su nueva contraseña.'),
(280, 2, 'Datos de usuario no válido'),
(281, 2, 'Fecha'),
(282, 2, 'Mostrar detalles'),
(283, 2, 'Ocultar detalles'),
(284, 2, 'me'),
(285, 2, 'Lo sentimos, la contraseña no se puede cambiar por favor informe al administrador.'),
(286, 2, 'Passwod recuperación'),
(287, 2, 'Si desea cambiar su contraseña,'),
(288, 2, 'Haga clic aquí'),
(289, 2, 'Por favor, introduzca la contraseña!'),
(290, 2, 'La contraseña es srength weak.Choose otro.'),
(291, 2, 'Muy débil'),
(292, 2, 'Débil'),
(293, 2, 'Bueno'),
(294, 2, 'Fuerte'),
(295, 2, 'Muy fuerte'),
(296, 2, 'Seguridad de la contraseña'),
(297, 2, 'La clave no entró'),
(298, 2, 'Por favor introduce el identificador de correo electrónico alternativa en el momento de su registro que ha entrado.'),
(299, 2, 'Por favor introduce el correo electrónico alternativa nueva id.'),
(300, 2, 'Por favor revise su correo electrónico alternativa y continuar el proceso de recuperación de contraseña'),
(301, 2, 'Aceptar'),
(302, 2, 'Para obtener una nueva contraseña'),
(309, 2, 'Registrarse'),
(310, 2, 'Añadir a'),
(311, 2, 'Eliminar de la'),
(312, 2, 'Ha registrado.'),
(314, 2, 'Número de teléfono no puede ser nulo.'),
(315, 2, 'Ver grupo de {foldername} contactos.'),
(313, 2, 'En este momento está usando {memoryused} MB.'),
(316, 2, 'Uso de la memoria'),
(317, 2, 'El nombre de la carpeta que ha elegido ya existe. Por favor, pruebe con otro nombre.'),
(318, 2, 'En este momento está usando {percent}% de su {totalmemory} MB.'),
(321, 2, 'Recuperación de la contraseña'),
(322, 2, 'Verificar su Identidad'),
(323, 2, 'Buscar mensaje'),
(324, 2, 'Búsqueda Contacto'),
(325, 2, 'Usted debe dar un nombre al grupo.'),
(326, 2, 'nombre deseado entrada contiene caracteres no válidos'),
(327, 2, 'nombre deseado entrada contiene characters.Please válido escoger otra nombre_usuario'),
(328, 2, 'Idiomas'),
(329, 2, 'Defecto'),
(330, 2, 'Por favor, especifique al menos un destinatario.'),
(331, 2, 'Enviar mensaje sin asunto?'),
(332, 2, 'Enviar este mensaje sin texto en el cuerpo?'),
(333, 2, 'Cargando página'),
(334, 2, 'Nombre de acceso deseado contiene caracteres no válidos.'),
(335, 2, 'Nombre de acceso deseado debe comenzar con una letra.'),
(336, 2, 'Panel 1'),
(337, 2, 'Mensajes por página'),
(338, 2, 'Por favor, seleccione cualquier regla de filtrado'),
(340, 2, 'Esta operación no está permitida en la versión demo.'),
(303, 2, 'El nombre del grupo es demasiado largo. Por favor, pruebe con otro nombre'),
(304, 2, 'Ninguna conversación ha sido seleccionado'),
(305, 2, '{number} contacto se ha añadido al grupo de {groupname}'),
(306, 2, '{number} contacto se ha eliminado del grupo {groupname}.'),
(307, 2, 'Palabras clave no puede ser nulo!'),
(308, 2, 'Regístrese ahora'),
(319, 2, 'Tamaño de accesorios excede!'),
(320, 2, 'Nombre de usuario incorrecto'),
(14, 3, 'Effacer'),
(15, 3, 'Réponse'),
(16, 3, 'Répondre à tous'),
(17, 3, 'Avant'),
(18, 3, 'Plus d\'actions'),
(19, 3, 'Boîte de réception'),
(20, 3, 'Ébauche'),
(21, 3, 'Sent'),
(22, 3, 'Déchets'),
(23, 3, 'Personnel'),
(24, 3, 'Nouveau Contact'),
(25, 3, 'Nouveau groupe'),
(26, 3, 'Éditer'),
(27, 3, 'Importation'),
(28, 3, 'Exportation'),
(29, 3, 'Sync'),
(30, 3, 'Pas de mails à afficher'),
(31, 3, 'Pour'),
(32, 3, 'Cc'),
(33, 3, 'Cci'),
(34, 3, 'Sujet'),
(35, 3, 'Les pièces jointes'),
(36, 3, 'Enregistrer brouillons'),
(37, 3, 'Envoyer'),
(38, 3, 'Message'),
(39, 3, 'Déconnexion'),
(40, 3, 'Prénom'),
(41, 3, 'Nom de famille'),
(42, 3, 'Email'),
(43, 3, 'Date de naissance'),
(44, 3, 'Titre'),
(45, 3, 'Entreprise'),
(46, 3, 'Téléphone'),
(47, 3, 'Adresse'),
(48, 3, 'Site Web'),
(49, 3, 'Groupe'),
(50, 3, 'Ajouter'),
(51, 3, 'Aucun sujet'),
(52, 3, 'Sur'),
(53, 3, 'Sous'),
(54, 3, 'À partir de'),
(55, 3, 'days ago'),
(56, 3, 'hours ago'),
(57, 3, 'après-midi'),
(58, 3, 'il ya une heure'),
(59, 3, 'Jeter'),
(60, 3, 'Joindre plusieurs fichiers'),
(61, 3, 'Tous'),
(62, 3, 'jj / mm / aaaa'),
(63, 3, 'Enregistrez vos contacts'),
(64, 3, 'Groupes'),
(65, 3, 'ss'),
(66, 3, 'Aucun contact dans ce dossier.'),
(67, 3, 'Aucun détail des contacts dans ce dossier.'),
(68, 3, 'Webmail'),
(69, 3, 'Paramètres de l\'agenda'),
(70, 3, 'Spam'),
(71, 3, 'Filtres'),
(72, 3, 'Options'),
(73, 3, 'Mot de passe'),
(74, 3, 'Marquer comme lu'),
(75, 3, 'Marquer comme non lu'),
(76, 3, 'Il s\'agit de votre nom de connexion compte de messagerie.'),
(77, 3, '2 Pane'),
(78, 3, '3 volet'),
(79, 3, 'Enregistrer les paramètres'),
(80, 3, 'Supprimer la sélection'),
(81, 3, 'Aucun e-mails sont actuellement filtré.'),
(82, 3, 'Spécifiez le dossier dans lequel la règle remettra à'),
(83, 3, 'Ajouter étoiles'),
(84, 3, 'Retirer étoiles'),
(85, 3, 'Sélectionner l\'ensemble des'),
(86, 3, 'Désélectionner tous les'),
(87, 3, 'La nouvelle règle'),
(88, 3, 'Corps'),
(89, 3, 'Exact Match'),
(90, 3, 'Commence par'),
(91, 3, 'Se termine par'),
(92, 3, 'Contient'),
(93, 3, 'Et'),
(94, 3, 'La règle de filtrage'),
(95, 3, 'Action'),
(96, 3, '{rule_from} {from_match} \'{from_value}\' {end1} {rule_subject} {subject_match} \'{subject_value}\' {end2}{rule_body} {body_match} \'{body_value}\''),
(97, 3, 'Indiquez une liste d\'adresses e-mail, nom de domaine dans votre liste blanche, chacun doivent être séparés par une virgule. Tout courriel qui correspond sera automatiquement marqués comme approuvés sans être classé comme spam.'),
(98, 3, 'Indiquez une liste d\'adresses e-mail, nom de domaine dans votre liste noire, chacun doivent être séparés par une virgule. Tout courriel qui correspond sera automatiquement marqués comme spam.'),
(99, 3, 'Modifier la règle'),
(100, 3, 'EditRule'),
(101, 3, 'Télécharger'),
(102, 3, 'Voir l\'image'),
(103, 3, 'Nom d\'utilisateur ne peut pas être laissé en blanc.'),
(104, 3, 'Mot de passe ne peut pas être laissé en blanc.'),
(105, 3, 'Nom de connexion demandé'),
(106, 3, 'Créer mon compte'),
(107, 3, 'Vérifiez la disponibilité'),
(108, 3, 'Désolé, votre nom d\'utilisateur ne peut pas être supérieure à 32 caractères.'),
(109, 3, 'Désolé, votre nom de connexion doit être comprise entre {min_usernamelength} et 32 caractères.'),
(110, 3, '{mailid} est disponible.'),
(111, 3, '{mailid}  n\'est pas disponible.'),
(112, 3, 'Prénom ne peut pas être laissé en blanc.'),
(113, 3, 'Nom de famille ne peut pas être laissé en blanc.'),
(114, 3, 'Login souhaité nom ne peut être laissée en blanc.'),
(115, 3, 'Mot de passe actuel'),
(116, 3, 'Nouveau mot de passe'),
(117, 3, 'Confirmer Mot de passe'),
(118, 3, 'Confirmer mot de passe ne peut pas être laissé en blanc.'),
(119, 3, 'Nouveau mot de passe ne peut pas être laissé en blanc.'),
(120, 3, 'Question de sécurité'),
(122, 3, 'Sexe'),
(123, 3, 'Pays'),
(124, 3, 'nom de connexion non valide'),
(125, 3, 'Question de sécurité ne peut pas être laissé en blanc.'),
(126, 3, 'Réponse ne peut être laissée en blanc.'),
(127, 3, 'domaine des sexes ne peut être laissée en blanc.'),
(128, 3, 'S\'il vous plaît sélectionnez le champ jour.'),
(129, 3, 'S\'il vous plaît sélectionnez le champ mois.'),
(130, 3, 'S\'il vous plaît sélectionnez le champ de l\'année.'),
(131, 3, 'S\'il vous plaît choisir un pays.'),
(132, 3, 'Les mots de passe ne correspondent pas.'),
(133, 3, 'Jour'),
(134, 3, 'Mois'),
(135, 3, 'Année'),
(136, 3, 'Choisissez-en un'),
(137, 3, 'Mâle'),
(138, 3, 'Féminin'),
(139, 3, 'Sélectionner un pays'),
(140, 3, 'Choisissez une question........'),
(141, 3, 'Quel est le prénom de votre meilleur ami d\'enfance?'),
(142, 3, 'Quel était le nom de votre école primaire?'),
(143, 3, 'Quel est le nom de la première société, vous avez travaillé?'),
(144, 3, 'Quel est votre petit nom?'),
(145, 3, 'Quel était votre premier numéro de téléphone?'),
(146, 3, 'Donnez à ma propre question'),
(147, 3, 'Vérification des mots'),
(148, 3, 'varification Image échoué. S\'il vous plaît essayez de nouveau.'),
(149, 3, 'Vérification des mots ne peut pas être laissé en blanc.'),
(150, 3, 'Déjà membre'),
(151, 3, 'Blanche des expéditeurs'),
(152, 3, 'Liste noire des expéditeurs'),
(153, 3, 'Activer l\'avenir'),
(154, 3, 'Transférer des messages'),
(155, 3, 'Activer Autoreply'),
(156, 3, 'Autoreply message'),
(157, 3, 'De'),
(158, 3, 'S\'il vous plaît Entrez l\'email ID.'),
(159, 3, 'Blancs E-mail ID.'),
(160, 3, 'Autoreply message ne peut pas être laissé en blanc.'),
(161, 3, 'Suceessfully enregistré vos paramètres.'),
(162, 3, 'S\'il vous plaît sélectionnez l\'option Paramètres.'),
(163, 3, 'Résultats de la recherche pour {search} dans le {folder}'),
(164, 3, 'Tous les dossiers'),
(165, 3, 'S\'il vous plaît sélectionnez le dossier.'),
(166, 3, 'Règle deja existent.'),
(167, 3, 'Nom du compte'),
(168, 3, 'Affichage par défaut'),
(169, 3, 'Langue'),
(170, 3, 'Thèmes'),
(171, 3, 'Signature'),
(172, 3, 'S\'il vous plaît sélectionnez un contact.'),
(173, 3, 'Le message a été envoyé'),
(174, 3, '1 conversation a été déplacé dans la corbeille'),
(175, 3, '1 conversation a été déplacé de {fromfolder} à {tofolder}'),
(176, 3, 'Désélectionner'),
(177, 3, '{number} conversations ont été placées dans la corbeille'),
(178, 3, '{number}  conversations ont été placées de {fromfolder} à {tofolder}'),
(179, 3, 'Modifier le contact'),
(180, 3, 'Modifier le groupe de'),
(181, 3, '{number}  conversations ont été supprimés donne en permanence'),
(182, 3, '1 conversation a été supprimée donne en permanence'),
(183, 3, '1 conversation a été marqué comme lu'),
(184, 3, '{number} les conversations ont été marqués comme lus'),
(185, 3, '1 conversation a été favoris'),
(186, 3, '{number} les conversations ont été favoris'),
(187, 3, '1 conversation a été marquée comme non lus'),
(188, 3, '{number} les conversations ont été marqués comme non lus'),
(189, 3, '1 conversation a été étoilée'),
(190, 3, '{number} les conversations ont été supprimées des éléments suivis'),
(191, 3, '1 conversation a été marqué comme spam'),
(192, 3, '{number} conversations ont été marquées comme spam'),
(193, 3, 'Domaine {domain} existent dans les deux liste blanche et liste noire! S\'il vous plaît le supprimer.'),
(194, 3, 'Adresse e-mail {email} existent dans les deux liste blanche et liste noire! S\'il vous plaît le supprimer.'),
(195, 3, 'Les paramètres ont été mis à jour.'),
(196, 3, 'S\'il vous plaît remplir atleast un champ.'),
(197, 3, 'Etes-vous sûr de vouloir supprimer'),
(198, 3, 'D\'ajouter un nouveau contact.'),
(199, 3, '{number} contact a été supprimé.'),
(200, 3, 'connexion Blancs! Nom d\'utilisateur ou mot de passe est incorrect.'),
(201, 3, 'Ajouter Cc'),
(202, 3, 'Ajouter Cci'),
(203, 3, 'Groupes existants'),
(204, 3, 'Cette action se traduira par la perte de données pour permanently.Do vous voulez continuer?'),
(205, 3, 'Favoris'),
(206, 3, 'Supprimer le contact'),
(207, 3, 'Votre mail a été enregistrée sur les projets'),
(208, 3, 'Résultats de la recherche pour \'{searchvalue}\' dans \'{group}\''),
(209, 3, 'Mes Contacts'),
(210, 3, 'Tous les groupes'),
(211, 3, 'Autres contacts\r\n'),
(212, 3, 'Contacts dans le monde'),
(213, 3, 'Renommer'),
(214, 3, 'Groupe a été renommé en {groupname}.'),
(215, 3, 'Groupe {groupname} a été créé.'),
(216, 3, 'Les images ne s\'affichent'),
(217, 3, 'Afficher les images ci-dessous'),
(218, 3, 'Toujours afficher les images à partir de'),
(223, 3, 'Le contact a été ajouté.'),
(219, 3, 'Groupe a été supprimé avec succès.'),
(220, 3, 'Dossier a été renommé en {foldername}.'),
(221, 3, 'Dossier {foldername} a été créé.'),
(222, 3, 'Dossier a été supprimé avec succès.'),
(224, 3, 'Courrier électronique ne peut pas être laissé en blanc.'),
(225, 3, 'S\'il vous plaît entrer une adresse email valide.'),
(226, 3, 'S\'il vous plaît, entrez un numéro de téléphone valide.'),
(227, 3, 'Information de contact a été enregistré.'),
(228, 3, 'Contacts existent déjà.'),
(229, 3, 'Déjà enregistré. Choisir un autre nom d\'utilisateur.'),
(230, 3, 'Groupe {groupname} existent déjà. S\'il vous plaît choisir un autre nom.'),
(231, 3, 'S\'il vous plaît sélectionner le fuseau horaire.'),
(232, 3, 'Time Zone'),
(233, 3, 'Sélectionnez le fuseau horaire'),
(234, 3, 'Pièce jointe format de fichier non pris en charge'),
(235, 3, 'Désolé, votre mot de passe ne peut pas être supérieure à 32 caractères.'),
(236, 3, 'Désolé, votre mot de passe doit être compris entre 6 et 32 caractères.'),
(237, 3, 'Désolé, votre mot de passe de confirmer doit être comprise entre 6 et 32 caractères.'),
(238, 3, 'Désolé, votre mot de passe confirmer ne peut pas être supérieure à 32 caractères.'),
(239, 3, 'Règle de filtrage supprimé avec succès.'),
(240, 3, 'Vous souhaitez supprimer cette règle de filtrage. Appuyez sur OK pour continuer.'),
(241, 3, 'Tous les champs sont vides!'),
(242, 3, 'S\'il vous plaît entrez le mot de passe actuel!'),
(243, 3, 'S\'il vous plaît entrez le nouveau mot de passe!'),
(244, 3, 'S\'il vous plaît entrez le mot de passe confirmer!'),
(245, 3, 'Mot de passe actuel est incorrecte!'),
(246, 3, 'Nouveau mot de passe et mots de passe Confirmez sont différents!'),
(247, 3, 'expéditeurs liste blanche contient la liste répétées nom de domaine. S\'il vous plaît le supprimer!'),
(248, 3, 'expéditeurs liste blanche contenant la liste des courriels répétés. S\'il vous plaît le supprimer!'),
(249, 3, 'expéditeurs liste noire contient la liste email répétées. S\'il vous plaît le supprimer!'),
(250, 3, 'expéditeurs liste noire contient la liste répétées nom de domaine. S\'il vous plaît le supprimer!'),
(251, 3, 'Votre domaine d\'extension {extension} n\'est pas correcte'),
(252, 3, 'Nom de domaine ne devrait pas commencer sont fin avec \'-\''),
(253, 3, 'Votre nom de domaine ne devraient pas avoir des caractères spéciaux'),
(254, 3, 'Votre nom de domaine est trop court ou à long'),
(255, 3, 'expéditeurs liste blanche contenant l\'adresse mail valide.'),
(256, 3, 'expéditeurs liste noire contenant l\'adresse mail valide.'),
(257, 3, 'S\'il vous plaît insérez une ou l\'autre liste blanche ou liste noire des expéditeurs de détails.'),
(258, 3, 'Email ID répétées. S\'il vous plaît Retirez!'),
(259, 3, 'Autoreply sujet ne peut être laissée en blanc.'),
(260, 3, 'S\'il vous plaît entrez l\'email en avant id.'),
(261, 3, 'S\'il vous plaît entrer dans le message de réponse automatique.'),
(262, 3, 'S\'il vous plaît entrez le sujet réponse automatique.'),
(265, 3, 'Créer un nouveau compte'),
(266, 3, 'Mail Web Libe'),
(267, 3, 'Annuler'),
(268, 3, 'Continuer'),
(269, 3, 'Vous avez oublié votre mot de passe'),
(270, 3, 'S\'il vous plaît entrer votre nom d\'utilisateur.'),
(271, 3, 'Blancs de l\'utilisateur'),
(272, 3, 'Autre courriel'),
(273, 3, 'Répondez à la question'),
(274, 3, 'Votre question'),
(275, 3, 'OU'),
(276, 3, 'Soumettre'),
(277, 3, 'S\'il vous plaît entrer la réponse.'),
(278, 3, 'Votre nouveau mot de passe est'),
(279, 3, 'S\'il vous plaît Connectez-vous maintenant avec votre nouveau mot de passe.'),
(280, 3, 'détails user Blancs'),
(281, 3, 'Date'),
(282, 3, 'Voir les détails'),
(283, 3, 'Masquer les détails'),
(284, 3, 'moi'),
(285, 3, 'Désolé, mot de passe ne peut pas être changé s\'il vous plaît informer l\'administrateur.'),
(286, 3, 'Passwod récupération'),
(287, 3, 'Si vous voulez changer votre mot de passe,'),
(288, 3, 'Cliquez ici'),
(289, 3, 'S\'il vous plaît entrez le mot de passe!'),
(290, 3, 'srength mot de passe est weak.Choose un autre.'),
(291, 3, 'Très faible'),
(292, 3, 'Faible'),
(293, 3, 'Bon'),
(294, 3, 'Fort'),
(295, 3, 'Très fort'),
(296, 3, 'force Mot de passe'),
(297, 3, 'Mot de passe n\'est pas entré'),
(298, 3, 'S\'il vous plaît entrer dans le e-mail secondaire id au moment de votre inscription vous avez inscrits.'),
(299, 3, 'S\'il vous plaît entrez le nouveau suppléant email id.'),
(300, 3, 'S\'il vous plaît vérifier votre e-mail secondaire et de poursuivre le processus de récupération de mot de passe'),
(301, 3, 'OK'),
(302, 3, 'Pour obtenir un nouveau mot de passe'),
(303, 3, 'Le nom du groupe est trop long. vous plaît essayez un autre nom'),
(304, 3, 'Pas de conversation a été sélectionné'),
(305, 3, '{number} contact a été ajouté au groupe {groupname}'),
(306, 3, '{number} contact a été retiré du groupe {groupname}.'),
(307, 3, 'Mot-clé ne peut pas être nul!'),
(308, 3, 'Inscrivez-vous maintenant'),
(309, 3, 'Identifiez-vous'),
(310, 3, 'Ajouter à'),
(311, 3, 'Retirer'),
(312, 3, 'Vous avez enregistré avec succès.'),
(319, 3, 'taille des pièces jointes dépasse!'),
(320, 3, 'Pseudo Blancs'),
(314, 3, 'Numéro de téléphone ne peut pas être null.'),
(315, 3, 'Voir le groupe {foldername} contacts.'),
(313, 3, 'Vous utilisez actuellement {memoryused} Mo.'),
(316, 3, 'Utilisation de la mémoire'),
(317, 3, 'Le nom du dossier que vous avez choisi existe déjà. S\'il vous plaît essayez un autre nom.'),
(318, 3, 'Vous utilisez actuellement {percent}% {totalmemory} de votre MB.'),
(321, 3, 'Password Recovery'),
(322, 3, 'Vérifiez votre identité'),
(323, 3, 'Rechercher dans les messages'),
(324, 3, 'Contact Recherche'),
(325, 3, 'Vous devez donner un nom au groupe.'),
(326, 3, 'Nom de connexion demandé contient des caractères invalides'),
(327, 3, 'Nom de connexion demandé contient characters.Please invalide choisir une autre loginname'),
(328, 3, 'Langues'),
(329, 3, 'Par défaut'),
(330, 3, 'S\'il vous plaît spécifier au moins un destinataire.'),
(331, 3, 'Envoyer le message sans objet?'),
(332, 3, 'Envoyer ce message sans texte dans le corps?'),
(333, 3, 'Chargement de la page'),
(334, 3, 'Identifiant souhaité contient des caractères invalides.'),
(335, 3, 'Login souhaité nom doit commencer par une lettre.'),
(336, 3, '1 volet'),
(337, 3, 'Mails page nominale'),
(338, 3, 'S\'il vous plaît sélectionnez une règle de filtrage'),
(339, 3, 'Installation de transfert automatique est disponible uniquement avec le tag \'valiyapalli.com @\' extension de domaine dans la version démo'),
(340, 3, 'Cette opération n\'est pas autorisée dans la version démo.'),
(341, 1, 'What\'s New in Libe Web Mail'),
(342, 1, 'Login to Libe Web Mail'),
(343, 1, 'Anti Spam Mail Service'),
(344, 1, 'Libe Web Mail comes with advanced spam filter methods which will makes sure your inbox is spam free.'),
(345, 1, 'Organize your Emails'),
(346, 1, 'Libe Web Mail now allows you to effectively organize your emails with custom folders and email grouping.'),
(347, 1, 'Multi Language Support'),
(348, 1, 'Want to manage your mailbox in the language you are most comfortable with? Libe Web Mail now comes with multi language support.'),
(349, 1, 'Don\'t have an Libe Web Mail Account?'),
(350, 1, 'Sign Up!'),
(351, 1, 'Copyright © 2006-{year} www.liberyus.com, All Rights Reserved.'),
(352, 1, 'of'),
(341, 2, '¿Qué hay de nuevo en Webmail Libe'),
(342, 2, 'Inicie sesión para Libe Web Mail'),
(343, 2, 'Anti Spam servicio de correo'),
(344, 2, 'Libe Web Mail viene con métodos avanzados de filtro de spam que se asegura que su bandeja de entrada está libre de spam.'),
(345, 2, 'Organice sus mensajes de correo electrónico'),
(346, 2, 'Libe Web Mail ahora le permite organizar de forma efectiva su correo electrónico con carpetas personalizadas y agrupación de correo electrónico.'),
(347, 2, 'Soporte de idiomas múltiples'),
(348, 2, '¿Quieres controlar tu buzón de correo en el idioma que se sienta más cómodo? Libe Web Mail ahora viene con soporte multi idioma.'),
(349, 2, '¿Todavía no tienes una cuenta de Libe Web Mail?'),
(350, 2, '¡Inscríbete!'),
(351, 2, 'Copyright © 2006 - {year} www.liberyus.com Todos los derechos reservados.'),
(341, 3, 'Quoi de neuf dans Webmail Libe'),
(342, 3, 'Connectez-vous pour Libe Web Mail'),
(343, 3, 'Service de lutte contre le spam mail'),
(344, 3, 'Libe Web Mail est livré avec des méthodes avancées de filtre anti-spam qui fait que votre boîte de réception est un spam gratuitement.'),
(345, 3, 'Organiser vos e-mails'),
(346, 3, 'Libe Web Mail vous permet désormais d\'organiser efficacement vos e-mails avec des dossiers personnalisés et le groupement e-mail.'),
(347, 3, 'Support multi-langue'),
(348, 3, 'Vous souhaitez gérer votre boîte aux lettres dans la langue vous êtes le plus à l\'aise? Libe Web Mail est désormais livré avec support multi-langue.'),
(349, 3, 'Vous n\'avez pas de compte de courriel Web Libe?'),
(350, 3, 'Inscrivez-vous!'),
(351, 3, 'Copyright © 2006 - {year} www.liberyus.com, Tous droits réservés.'),
(352, 2, 'de'),
(352, 3, 'de'),
(353, 1, 'GMT'),
(353, 2, 'GMT'),
(353, 3, 'GMT'),
(354, 1, 'Password cannot be same as Desired Login Name'),
(354, 3, 'Mot de passe ne peut pas être la même que désiré Identifiant'),
(354, 2, 'La clave no puede ser el mismo que el Nombre de Usuario Deseadoa'),
(355, 1, 'Password cannot be same as username'),
(355, 3, 'Mot de passe ne peut pas être la même que nom d\'utilisateur'),
(355, 2, 'La clave no puede ser la misma como nombre de usuario'),
(356, 1, 'The folder name is too long. Please try another name.'),
(356, 2, 'El nombre de la carpeta es demasiado largo. Por favor, pruebe con otro nombre.'),
(356, 3, 'Le nom du dossier est trop long. S\'il vous plait essayez un autre nom.'),
(357, 1, 'Operation not allowed!!!'),
(358, 1, 'User Login Area'),
(357, 2, 'La operación no permitido!'),
(358, 2, 'Zona de Usuarios Login'),
(357, 3, 'Opération non autorisée!'),
(358, 3, 'Zone de connexion de utilisateur'),
(359, 1, 'You must answer one seurity question'),
(359, 3, 'Vous devez répondre a une question seurity'),
(359, 2, 'Usted debe contestar una pregunta seurity'),
(360, 1, 'Refresh'),
(360, 2, 'Actualizar'),
(360, 3, 'Actualiser'),
(361, 1, 'Profile'),
(361, 2, 'Perfil'),
(361, 3, 'Profil'),
(362, 1, 'Profile has been successfully updated'),
(362, 2, 'El perfil ha sido actualizado correctamente'),
(362, 3, 'Le profil a été mis à jour'),
(363, 1, 'Chat'),
(364, 1, 'Sign into chat'),
(365, 1, 'Available'),
(366, 1, 'Custom message'),
(367, 1, 'Busy'),
(368, 1, 'Sign out of chat'),
(369, 1, 'Invisible'),
(370, 1, 'Chat'),
(371, 1, 'Options'),
(372, 1, 'Invite'),
(373, 1, 'Set status here'),
(374, 1, 'wants to be able to chat with you. Okay?'),
(375, 1, 'yes'),
(376, 1, 'no'),
(377, 1, 'Tiny'),
(378, 1, 'Small'),
(379, 1, 'Medium'),
(380, 1, 'Large'),
(381, 1, 'Invite to chat'),
(382, 1, 'Chat with'),
(383, 1, 'Time'),
(384, 1, 'Sub:chat with'),
(385, 1, 'Chat Invitations'),
(386, 1, 'Type the email address of some people that you would like to invite'),
(387, 1, 'You can type email addresses here separated by commas'),
(388, 1, 'You are almost done, just pick a couple of friends to invite.'),
(389, 1, 'Sorry, some of the addresses that you entered look invalid. Double-check the addresses in the box above and try again.'),
(390, 1, 'The user cannot be invitied as he/she is a person outside this domain.'),
(391, 1, 'The user you have entered does not exist.'),
(392, 1, 'Send Invites'),
(393, 1, 'Your internet connection has lost.Please check your internet connection.'),
(394, 1, 'Please sign in to chat first.'),
(395, 1, 'Add People to this chat'),
(396, 1, 'Group chat'),
(397, 1, 'Says'),
(398, 1, 'Chat History'),
(399, 1, 'Save chat history'),
(400, 1, 'Never save chat history'),
(401, 1, 'Chatwindow size'),
(402, 1, 'Sounds'),
(403, 1, 'Sounds on'),
(404, 1, 'Sounds off'),
(405, 1, 'My alert sound'),
(406, 1, 'Valid Format'),
(407, 1, 'Smileys'),
(408, 1, 'Smileys on'),
(409, 1, 'Smileys off'),
(410, 1, 'My Picture'),
(411, 1, 'Change Picture'),
(412, 1, 'Valid Formats'),
(413, 1, 'Please upload files of valid formats.'),
(414, 1, 'No match for'),
(415, 1, '{user} has joined.'),
(416, 1, 'This is now a group chat.'),
(417, 1, 'Invited'),
(418, 1, '{firstname} is offline. Messages you send will be delivered when {firstname} comes online.'),
(419, 1, '{firstname} is busy. You may be interrupting.'),
(420, 1, '{fname} is typing'),
(421, 1, '{fname} has entered text'),
(422, 1, '{user} is not in your chatlist. You can only invite current chatlist friends.'),
(423, 1, 'Sent at {time} on {day}'),
(424, 1, 'Invalid domain.'),
(425, 1, '{firstname} is not currently online.'),
(426, 1, '{user} is already in this chat.'),
(427, 1, 'You have invited {firstname} to this chat.'),
(428, 1, '{fullname} has left'),
(429, 1, 'Chats'),
(430, 1, 'lines'),
(431, 1, 'Last'),
(432, 1, 'Prev'),
(433, 1, 'Next'),
(434, 1, 'Please choose a mail'),
(435, 1, 'Please choose a single mail'),
(436, 1, 'to'),
(437, 1, 'Please fill the reciepient field'),
(438, 1, 'Maximize'),
(439, 1, 'Minimize'),
(440, 1, 'Registration failed. Please try again.'),
(441, 1, 'Could not connected to server.Please try again.'),
(442, 1, 'First'),
(443, 1, 'Mark as star'),
(444, 1, 'Mark as unstar'),
(445, 1, 'Please select one or more conversation(s)'),
(446, 1, 'The selected conversation has been moved to Trash'),
(447, 1, 'The selected conversation has been moved to '),
(448, 1, 'Operation not performed'),
(449, 1, 'Your message has been saved to draft'),
(450, 1, 'Close'),
(451, 1, 'Loading'),
(363, 2, 'Chat'),
(364, 2, 'Entra en el chat'),
(365, 2, 'Disponible'),
(366, 2, 'Mensaje personalizado'),
(367, 2, 'Ocupada'),
(368, 2, 'Salir del chat'),
(369, 2, 'Invisible'),
(370, 2, 'Chat'),
(371, 2, 'Opciones'),
(372, 2, 'Invitar'),
(373, 2, 'Establecer el estado aquí'),
(374, 2, 'quiere ser capaz de charlar con usted. ¿De acuerdo?'),
(375, 2, 'sí'),
(376, 2, 'No'),
(377, 2, 'Pequeños'),
(378, 2, 'Pequeñas'),
(379, 2, 'Medio'),
(380, 2, 'Grande'),
(381, 2, 'Invitar a un chat'),
(382, 2, 'Habla con'),
(383, 2, 'Tiempo'),
(384, 2, 'Tema: chatear con'),
(385, 2, 'Invitaciones al chat'),
(386, 2, 'Escriba la dirección de correo electrónico de algunas personas que le gustaría invitar a'),
(387, 2, 'Usted puede escribir aquí las direcciones de correo electrónico separadas por comas'),
(388, 2, 'Usted está casi hecho, sólo debes elegir un par de amigos para invitar.'),
(389, 2, 'Lo sentimos, algunas de las direcciones que ha introducido no son válidas. Compruebe las direcciones en el cuadro de arriba y vuelve a intentarlo.'),
(390, 2, 'El usuario no puede invitied como él / ella es una persona fuera de este dominio'),
(391, 2, 'El usuario que ha introducido no existe.'),
(392, 2, 'Enviar invitaciones'),
(393, 2, 'Su conexión a internet ha lost.Please compruebe su conexión a Internet.'),
(394, 2, 'Accede a conversar primero.'),
(395, 2, 'Añadir gente a este chat'),
(396, 2, 'Chat de grupo'),
(397, 2, 'Dice'),
(398, 2, 'Historial de chat'),
(399, 2, 'Guardar el historial de chat'),
(400, 2, 'No guardar el historial de chat'),
(401, 2, 'Tamaño de la ventana de chat'),
(402, 2, 'Sonidos'),
(403, 2, 'Sonidos en'),
(404, 2, 'Sonidos de'),
(405, 2, 'Mi sonido de alerta'),
(406, 2, 'Válido Formato'),
(407, 2, 'Smileys'),
(408, 2, 'Smileys en'),
(409, 2, 'Smileys fuera'),
(410, 2, 'Mi imagen'),
(411, 2, 'Cambiar imagen'),
(412, 2, 'Los formatos válidos'),
(413, 2, 'Por favor, sube los archivos de formatos válidos.'),
(414, 2, 'No ha obtenido ninguna'),
(415, 2, '{user} se ha unido.'),
(416, 2, 'Esto es ahora un chat de grupo.'),
(417, 2, 'Invitados'),
(418, 2, '{firstname} no está en línea. Los mensajes que envíes se entregarán cuando {firstname} se pone en línea.'),
(419, 2, '{firstname} está ocupado. Usted puede interrumpir.'),
(420, 2, '{fname} está escribiendo'),
(421, 2, '{fname} ha introducido texto'),
(422, 2, '{user} no está en tu chatlist. Sólo puede invitar a amigos actuales chatlist.'),
(423, 2, 'Enviado a {time} en {day}'),
(424, 2, 'Dominio no válido.'),
(425, 2, '{firstname} no está actualmente en línea.'),
(426, 2, '{user} ya está en este chat.'),
(427, 2, 'Te han invitado a {firstname} a este chat.'),
(428, 2, '{fullname} ha dejado'),
(429, 2, 'Chats'),
(430, 2, 'líneas'),
(431, 2, 'Última'),
(432, 2, 'Anterior'),
(433, 2, 'Siguiente'),
(434, 2, 'Por favor, elija un e-mail'),
(435, 2, 'Por favor, elija una simple carta'),
(437, 2, 'Por favor, rellene el campo reciepient'),
(438, 2, 'Maximizar'),
(439, 2, 'Reducir al mínimo'),
(440, 2, 'El registro ha fallado. Por favor, inténtelo de nuevo.'),
(441, 2, 'No se pudo conectar a server.Please vuelva a intentarlo.'),
(442, 2, 'En primer lugar'),
(443, 2, 'Marcar como estrella'),
(444, 2, 'Marcar como unstar'),
(445, 2, 'Por favor, seleccione una o más de conversación (s)'),
(446, 2, 'La conversación seleccionado ha sido movido a la papelera'),
(447, 2, 'La conversación seleccionado ha sido movido a'),
(448, 2, 'La operación no se realiza'),
(449, 2, 'Su mensaje se ha guardado en el proyecto de'),
(450, 2, 'Cerrar'),
(451, 2, 'Cargando'),
(363, 3, 'Chat'),
(364, 3, 'Inscrivez-vous au chat'),
(365, 3, 'Disponible'),
(366, 3, 'Message personnalisé'),
(367, 3, 'Occupé'),
(368, 3, 'Inscrivez-vous sur le chat'),
(369, 3, 'Invisible'),
(370, 3, 'Chat'),
(371, 3, 'Options'),
(372, 3, 'Inviter'),
(373, 3, 'Définir le statut ici'),
(374, 3, 'veut être en mesure de discuter avec vous. D\'accord?'),
(375, 3, 'oui'),
(376, 3, 'pas'),
(377, 3, 'Tiny'),
(378, 3, 'Small'),
(379, 3, 'Medium'),
(380, 3, 'Large'),
(381, 3, 'Inviter à chatter'),
(382, 3, 'Chat avec'),
(383, 3, 'Temps'),
(384, 3, 'Sous: discuter avec'),
(385, 3, 'Invitations Chat'),
(386, 3, 'Tapez l\'adresse e-mail de certaines personnes que vous souhaitez inviter'),
(387, 3, 'Vous pouvez envoyer un courriel type adresses séparées par des virgules ici'),
(388, 3, 'Vous avez presque fini, il suffit de choisir un couple d\'amis à inviter.'),
(389, 3, 'Désolé, quelques-unes des adresses que vous avez entré comparer invalide. Double-vérifier les adresses dans la case ci-dessus et essayez à nouveau.'),
(390, 3, 'L\'utilisateur ne peut pas être invitied comme il / elle est une personne hors de ce domaine.'),
(391, 3, 'L\'utilisateur que vous avez saisi n\'existe pas.'),
(392, 3, 'Envoyer des invitations'),
(393, 3, 'Votre connexion Internet est lost.Please vérifier votre connexion internet.'),
(394, 3, 'S\'il vous plaît Inscrivez-vous au chat en premier.'),
(395, 3, 'Ajouter des personnes à ce chat'),
(396, 3, 'Groupe de discussion'),
(397, 3, 'Says'),
(398, 3, 'Historique des chats'),
(399, 3, 'Enregistrer l\'historique des chats'),
(400, 3, 'Ne jamais enregistrer l\'historique des chats'),
(401, 3, 'Fenêtre de chat de taille'),
(402, 3, 'Sons'),
(403, 3, 'Sons sur'),
(404, 3, 'Les sons hors'),
(405, 3, 'Mon alerte sonore'),
(406, 3, 'Suffrages Format'),
(407, 3, 'Smileys'),
(408, 3, 'Smileys sur'),
(409, 3, 'Smileys off'),
(410, 3, 'Mon image'),
(411, 3, 'Modifier l\'image'),
(412, 3, 'Formats valides'),
(413, 3, 'S\'il vous plaît télécharger des fichiers de formats valides.'),
(414, 3, 'Aucun résultat pour'),
(415, 3, '{user} a rejoint.'),
(416, 3, 'C\'est maintenant un chat en groupe.'),
(417, 3, 'Invité'),
(418, 3, '{firstname} est déconnecté. Les messages que vous envoyez seront livrés lorsque {firstname} est en ligne.'),
(419, 3, '{firstname} est occupé. Vous pouvez être interrompu.'),
(420, 3, '{fname} est de taper'),
(421, 3, '{fname} a entré du texte'),
(422, 3, '{user} n\'est pas dans votre chatlist. Vous ne pouvez inviter des amis chatlist actuelle.'),
(423, 3, 'Envoyé à {time} sur {day}'),
(424, 3, 'Blancs de domaine.'),
(425, 3, '{firstname} n\'est pas en ligne.'),
(426, 3, '{user} est déjà dans ce chat.'),
(427, 3, 'Vous avez invité {firstname} à ce chat.'),
(428, 3, '{fullname} a quitté'),
(429, 3, 'Chats'),
(430, 3, 'lignes'),
(431, 3, 'Dernière'),
(432, 3, 'Précédent'),
(433, 3, 'Suivant'),
(434, 3, 'S\'il vous plaît choisir un mail'),
(435, 3, 'S\'il vous plaît choisir un seul mail'),
(437, 3, 'S\'il vous plaît remplir le champ reciepient'),
(438, 3, 'Maximiser'),
(439, 3, 'Réduire au minimum'),
(440, 3, 'Echec de l\'enregistrement. S\'il vous plaît essayez de nouveau.'),
(441, 3, 'Ne pouvait pas connecté server.Please essayez à nouveau.'),
(442, 3, 'Première'),
(443, 3, 'Marquer comme star'),
(444, 3, 'Marquer comme désactiver le suivi'),
(445, 3, 'S\'il vous plaît sélectionner un ou plusieurs conversation (s)'),
(446, 3, 'La conversation sélectionnée a été déplacé dans la corbeille'),
(447, 3, 'La conversation sélectionnée a été déplacée à'),
(448, 3, 'Cette opération n\'est pas réalisée'),
(449, 3, 'Votre message a été enregistré sur le projet'),
(450, 3, 'Fermer'),
(451, 3, 'Chargement'),
(452, 1, 'Search'),
(453, 1, 'Select'),
(454, 1, 'My Settings'),
(455, 1, 'New Folder'),
(456, 1, 'Global'),
(457, 1, 'Minimum {length} characters required for login name'),
(458, 1, 'Maximum {length} characters required for login name'),
(459, 1, 'The selected conversations has been moved to Trash'),
(460, 1, 'The selected conversations has been moved to'),
(461, 1, 'Invalid Action'),
(454, 2, 'Mi configuración'),
(454, 3, 'Mes réglages'),
(453, 3, 'sélectionnez'),
(453, 2, 'seleccione'),
(452, 2, 'Búsqueda'),
(452, 3, 'Rechercher'),
(455, 2, 'Nueva carpeta'),
(455, 3, 'Nouveau dossier'),
(456, 2, 'Mundial'),
(456, 3, 'Global'),
(457, 3, 'Minimum {length} caractères requis pour nom de connexion'),
(457, 2, 'Mínimo {length} caracteres necesarios para el nombre de inicio de sesión'),
(458, 3, 'Maximum {length} caractères requis pour nom de connexion'),
(458, 2, 'Máxima {length} caracteres necesarios para el nombre de inicio de sesión'),
(459, 2, 'Las conversaciones seleccionado ha sido movido a la papelera'),
(459, 3, 'Les conversations sélectionnée a été déplacé dans la Corbeille'),
(460, 2, 'Las conversaciones seleccionado ha sido movido a'),
(460, 3, 'Les conversations sélectionnée a été déplacée à'),
(461, 2, 'No válido de acción'),
(461, 3, 'Blancs d\'action'),
(157, 2, 'Off'),
(462, 1, 'Search,add or invite'),
(462, 3, 'Rechercher, ajouter ou inviter'),
(462, 2, 'Busca, añade o invita'),
(463, 1, 'Configure Your Webmail Settings Below'),
(463, 2, 'Configurar las opciones de Webmail continuación'),
(463, 3, 'Configurer vos paramètres Webmail ci-dessous'),
(464, 1, 'Configure Your Spam Settings Below'),
(465, 1, 'Configure Your Email Filters Below'),
(466, 1, 'Configure Your Mail Options Below'),
(467, 1, 'Configure Your Chat Settings Below'),
(464, 2, 'Configurar los ajustes de correo no deseado Abajo'),
(465, 2, 'Configurar los filtros de correo Abajo'),
(466, 2, 'Configure las opciones de correo continuación'),
(467, 2, 'Configurar los ajustes de Chat Abajo'),
(464, 3, 'Configurez vos paramètres de spam ci-dessous'),
(465, 3, 'Configurer vos filtres email ci-dessous'),
(466, 3, 'Configurez vos options mail ci-dessous'),
(467, 3, 'Configurez vos paramètres de chat ci-dessous'),
(468, 1, 'Configure Your Profile Below'),
(469, 1, 'Configure Password Below'),
(468, 2, 'A continuación para configurar su perfil'),
(469, 2, 'Configurar contraseña abajo'),
(468, 3, 'Configurer votre profil ci-dessous'),
(469, 3, 'Mot de passe Configurer ci-dessous'),
(470, 1, 'Compose Mail'),
(471, 1, 'Uploading'),
(471, 2, 'Subir'),
(471, 3, 'Téléchargement'),
(470, 2, 'Redactar correo'),
(470, 3, 'Compose Mail'),
(472, 1, '(no subject)'),
(472, 2, '(sin asunto)'),
(472, 3, '(pas de sujet)'),
(473, 1, 'You must give a name to the folder.'),
(473, 2, 'Usted debe dar un nombre a la carpeta.'),
(473, 3, 'Vous devez donner un nom au dossier.'),
(474, 1, 'It\'s a reserved system folder. Please try another name.'),
(474, 2, 'Es una carpeta del sistema reservados. Inténtalo con otro nombre.'),
(474, 3, 'C\'est un dossier système réservés. S\'il vous plaît essayez un autre nom.'),
(475, 1, 'The group name you have chosen already exists. Please try another name.'),
(475, 2, 'El nombre del grupo que ha elegido ya existe. Inténtalo con otro nombre.'),
(475, 3, 'Le nom du groupe que vous avez choisi existe déjà. S\'il vous plaît essayez un autre nom.'),
(476, 1, 'The selected conversations deleted permanently'),
(476, 2, 'Las conversaciones seleccionada se eliminará de forma permanente'),
(476, 3, 'Les conversations sélectionnées supprimé définitivement'),
(477, 1, 'The selected conversation deleted permanently'),
(477, 2, 'La conversación seleccionada se eliminará de forma permanente'),
(477, 3, 'La conversation sélectionnée supprimé définitivement'),
(478, 1, 'Change alert sound'),
(478, 2, 'Cambiar sonido de alerta'),
(478, 3, 'Changer le son d\'alerte'),
(479, 1, 'Upload failed!!!.Try again'),
(479, 2, 'Error en la carga!. Inténtelo de nuevo'),
(479, 3, 'Échec du transfert!. Réessayez'),
(480, 1, 'Alternate Email cannot be left blank.'),
(480, 2, 'Correo electrónico alternativo, no puede dejarse en blanco.'),
(480, 3, 'Autre courriel ne peut pas être laissé en blanc.'),
(481, 1, '{firstname} did not receive your chat.'),
(481, 2, '{firstname} no ha recibido su chat.'),
(481, 3, '{firstname} n''avez pas reçu votre chat.'),
(482, 1, 'This group chat did not receive your chat.'),
(482, 2, 'Este chat de grupo no recibió su chat.'),
(482, 3, 'Ce chat de groupe n''a pas reçu de votre chat.'),
(483, 1, 'You are no longer signed into chat.'),
(483, 2, 'Usted ya no está firmado en el chat.'),
(483, 3, 'Vous n''êtes plus signé au chat.'),
(484, 1, 'You are currently disconnected from group chat. Messages cannot be delivered. You are no longer signed into chat.'),
(484, 2, 'Usted no se ha desconectado del grupo de chat. Los mensajes no pueden ser entregados. Usted ya no está firmado en el chat.'),
(484, 3, 'Vous êtes actuellement déconnecté du chat en groupe. Les messages ne peuvent pas être livrés. Vous n''êtes plus signé au chat.'),
(485, 1, 'Empty chat'),
(485, 2, 'Chat vacío'),
(485, 3, 'clavardage vide'),
(486, 1, 'For security reasons, this demo allows you to send emails only to other accounts registered in this demo website.'),
(486, 2, 'Por razones de seguridad, esta demo te permite enviar mensajes de correo electrónico sólo a otras cuentas registradas en este sitio web demo.'),
(486, 3, 'Pour des raisons de sécurité, cette démo vous permet d''envoyer des courriels uniquement à des comptes d''autres inscrits sur ce site de démonstration.'),
(487, 1, 'These messages were sent while you were offline.'),
(487, 2, 'Estos mensajes se enviaron cuando estabas desconectado.'),
(487, 3, 'Ces messages ont été envoyés pendant que vous étiez hors ligne.'),
(600, 1, 'Your message has been discarded.'),
(601, 1, 'Back to message'),
(602, 1, 'Sign out'),
(603, 1, 'No contacts to display.'),
(604, 1, 'Report Spam'),
(605, 1, 'From date'),
(606, 1, 'From time'),
(607, 1, 'To date'),
(608, 1, 'To time'),
(609, 1, 'Description'),
(610, 1, 'Save'),
(611, 1, 'Add Event'),
(612, 1, 'Reminder'),
(613, 1, 'minutes'),
(614, 1, 'hours'),
(615, 1, 'days'),
(616, 1, 'Week'),
(617, 1, 'Time zone'),
(618, 1, '(No event)'),
(619, 1, 'Sorry, you cannot create an event that ends before it starts.'),
(620, 1, 'Edit event'),
(621, 1, 'Configure Your Calendar Settings Below'),
(622, 1, 'Email Reminder'),
(623, 1, 'View events on mouseover'),
(624, 1, 'Event Details'),
(625, 1, 'More Details'),
(626, 1, 'To-do List'),
(627, 1, 'Edit Details'),
(628, 1, 'Notes'),
(629, 1, 'Back to To-do list'),
(630, 1, 'Today'),
(631, 1, 'Completed'),
(632, 1, 'Pending'),
(633, 1, 'You Want to Perform This Operation. Press OK to Continue.'),
(634, 1, 'Today List'),
(635, 1, 'View Completed List'),
(636, 1, 'View Pending List'),
(637, 1, 'View All'),
(638, 1, 'Clear Today List'),
(639, 1, 'Clear Completed List'),
(640, 1, 'Clear Pending List'),
(641, 1, 'Clear List'),
(642, 1, 'Empty Spam'),
(643, 1, 'Empty Trash'),
(644, 1, 'This action will affect all conversations in Spam. Are you sure you want to continue?'),
(645, 1, 'This action will affect all conversations in Trash. Are you sure you want to continue?'),
(646, 1, 'Print'),
(647, 1, 'Keyboard Shortcuts'),
(648, 1, 'Keyboard Shortcuts On'),
(649, 1, 'Keyboard Shortcuts Off'),
(650, 1, 'Learn More'),
(651, 1, 'Keyboard shortcuts help you save time by allowing you to never take your hands off the keyboard to use the mouse.'),
(652, 1, 'Upcoming Events'),
(653, 1, 'Choose Events Color'),
(654, 1, 'No events added'),
(600, 2, 'Su mensaje ha sido descartado.'),
(601, 2, 'Volver al mensaje'),
(602, 2, 'salir'),
(603, 2, 'No hay contactos para mostrar.'),
(604, 2, 'Reportar Spam'),
(605, 2, 'partir de la fecha'),
(606, 2, 'de vez en'),
(607, 2, 'hasta la fecha'),
(608, 2, 'a tiempo'),
(609, 2, 'descripción'),
(610, 2, 'ahorrar'),
(611, 2, 'Agregar evento'),
(612, 2, 'recordatorio'),
(613, 2, 'minutos'),
(614, 2, 'horas'),
(616, 2, 'semana'),
(617, 2, 'huso horario'),
(618, 2, '(Sin eventos)'),
(619, 2, 'Lo sentimos, no se puede crear un evento que finaliza antes de que comience.'),
(620, 2, 'editar evento'),
(621, 2, 'Configurar las opciones de calendario de abajo'),
(622, 2, 'recordatorio por correo electrónico'),
(623, 2, 'Ver eventos de mouseover'),
(624, 2, 'Detalles del evento'),
(625, 2, 'más detalles'),
(626, 2, 'Lista de tareas pendientes'),
(627, 2, 'editar detalles'),
(628, 2, 'notas'),
(629, 2, 'Volver a la lista de tareas pendientes'),
(630, 2, 'hoy'),
(631, 2, 'terminado'),
(632, 2, 'pendiente'),
(633, 2, 'Que desea realizar esta operación. Pulse Aceptar para continuar.'),
(634, 2, 'hoy en día la lista de'),
(635, 2, 'Ver lista completa'),
(636, 2, 'Ver la lista de espera'),
(637, 2, 'Ver todos'),
(638, 2, 'Lista de Hoy Despejado'),
(639, 2, 'Borrar lista Completado'),
(640, 2, 'Borrar lista espera'),
(641, 2, 'Borrar lista'),
(642, 2, 'spam vacía'),
(643, 2, 'Vaciar papelera'),
(644, 2, 'Esta acción afectará a todas las conversaciones en la carpeta Spam. ¿Está seguro que desea continuar?'),
(645, 2, 'Esta acción afectará a todas las conversaciones en la papelera. ¿Está seguro que desea continuar?'),
(646, 2, 'imprimir'),
(647, 2, 'Atajos de teclado'),
(648, 2, 'Atajos del teclado en'),
(649, 2, 'Atajos de teclado Off'),
(650, 2, 'Más información'),
(651, 2, 'Atajos de teclado ayudan a ahorrar tiempo al permitir nunca que sacar las manos del teclado para utilizar el ratón.'),
(652, 2, 'próximos eventos'),
(653, 2, 'Elegir color Eventos'),
(654, 2, 'No hay eventos añadido'),
(600, 3, 'Votre message a été supprimé.'),
(601, 3, 'Retour au message'),
(602, 3, 'Inscription à'),
(603, 3, 'Pas de contacts à afficher.'),
(604, 3, 'Rapport sur le Spam'),
(605, 3, 'De la date de'),
(606, 3, 'De temps'),
(607, 3, 'À ce jour'),
(608, 3, 'Pour le temps'),
(609, 3, 'description de'),
(610, 3, 'Enregistrer'),
(611, 3, 'Ajouter un évènement'),
(612, 3, 'rappel'),
(613, 3, 'minutes'),
(614, 3, 'heures'),
(615, 3, 'jours'),
(616, 3, 'Semaine'),
(617, 3, 'fuseau horaire'),
(618, 3, '(Aucun événement)'),
(619, 3, 'Désolé, vous ne pouvez pas créer un événement qui se termine avant qu''il ne commence.'),
(620, 3, 'événement Modifier'),
(621, 3, 'Configurer les paramètres de votre calendrier ci-dessous'),
(622, 3, 'Rappel email'),
(623, 3, 'Voir les événements sur le mouseover'),
(624, 3, 'Détails de l''événement'),
(625, 3, 'Plus de détails'),
(626, 3, 'To-do List'),
(627, 3, 'Modifier les détails'),
(628, 3, 'Remarques'),
(629, 3, 'Retour à la liste À faire'),
(630, 3, 'aujourd''hui'),
(631, 3, 'Terminé'),
(632, 3, 'Dans l''attente'),
(633, 3, 'Vous souhaitez effectuer cette opération. Appuyez sur OK pour continuer.'),
(634, 3, 'Liste aujourd''hui'),
(635, 3, 'Voir la liste Terminé'),
(636, 3, 'Voir la liste attente'),
(637, 3, 'Voir tous'),
(638, 3, 'Liste Aujourd''hui Effacer'),
(639, 3, 'Effacer la liste Terminé'),
(640, 3, 'Effacer la liste attente'),
(641, 3, 'Effacer la liste'),
(642, 3, 'Spam vide'),
(643, 3, 'Vider la corbeille'),
(644, 3, 'Cette action aura une incidence sur toutes les conversations dans les spams. Etes-vous sûr de vouloir continuer?'),
(645, 3, 'Cette action aura une incidence sur toutes les conversations dans la corbeille. Etes-vous sûr de vouloir continuer?'),
(646, 3, 'Imprimer'),
(647, 3, 'Raccourcis clavier'),
(648, 3, 'Raccourcis clavier sur'),
(649, 3, 'Raccourcis clavier Off'),
(650, 3, 'En savoir plus'),
(651, 3, 'Les raccourcis clavier vous aider à gagner du temps en vous permettant de ne jamais prendre vos mains du clavier pour utiliser la souris.'),
(652, 3, 'Événements à venir'),
(653, 3, 'Choisir la couleur des événements'),
(654, 3, 'Aucun événement ajoutée'),
(655, 1, 'Keyword'),
(656, 1, 'Has attachment'),
(657, 1, 'Advanced Search'),
(658, 1, 'Hide advanced search'),
(659, 1, 'Not Spam'),
(660, 1, 'The selected conversations has been unmarked as spam'),
(661, 1, 'Discard Drafts'),
(655, 2, 'palabra clave'),
(656, 2, 'Contiene archivos adjuntos'),
(657, 2, 'Búsqueda avanzada'),
(658, 2, 'Ocultar búsqueda avanzada'),
(659, 2, 'no es spam'),
(660, 2, 'Las conversaciones seleccionado ha sido marcado como spam'),
(661, 2, 'descartar borradores'),
(655, 3, 'Mot-clé'),
(656, 3, 'a de l''attachement'),
(657, 3, 'Recherche avancée'),
(658, 3, 'Masquer la recherche avancée'),
(659, 3, 'Pas Spam'),
(660, 3, 'Les conversations sélectionné a été banalisée comme spam'),
(661, 3, 'Supprimer les brouillons'),
(662, 1, 'The selected conversation has been unmarked as spam'),
(663, 1, 'Folder'),
(662, 2, 'La conversación seleccionada ha sido marcado como spam'),
(663, 2, 'carpeta'),
(662, 3, 'La conversation sélectionnée a été banalisée comme spam'),
(663, 3, 'dossier'),
(664, 1, 'Import'),
(664, 2, 'importación'),
(664, 3, 'Importer'),
(665, 1, 'Enter login details to fetch your contacts'),
(665, 2, 'Ingrese a su cuenta en busca de sus contactos'),
(665, 3, 'Entrez les informations de connexion pour récupérer vos contacts'),
(666, 1, 'Fetch Contacts'),
(666, 2, 'buscar contactos'),
(666, 3, 'Fetch Contacts'),
(667, 1, 'Tip of the Day'),
(667, 2, 'Sugerencia del día'),
(667, 3, 'Astuce du jour'),
(668, 1, 'Invalid Search'),
(668, 2, 'inválida Buscar'),
(668, 3, 'Recherche non valide'),
(669, 1, 'Search Options'),
(669, 2, 'Opciones de Búsqueda'),
(669, 3, 'options de recherche'),
(750, 1, 'Get Libe Web Mail on Your Smartphone'),
(750, 2, 'Obtener Webmail Libe en tu Smartphone'),
(750, 3, 'Obtenez Webmail Libe sur ​​votre smartphone'),
(751, 1, 'Provide a good solution for those needing their emails on the go. Get your emails on your mobile from anywhere in the world.'),
(751, 2, 'Proporcionar una buena solución para aquellos que necesitan sus mensajes de correo electrónico sobre la marcha. Recibe tus correos electrónicos en tu móvil desde cualquier lugar del mundo.'),
(751, 3, 'Fournir une bonne solution pour ceux qui ont besoin de leurs e-mails en déplacement. Obtenez vos e-mails sur votre mobile à partir de n\'importe où dans le monde.'),
(752, 1, 'Name'),
(752, 2, 'nombre'),
(752, 3, 'nom'),
(753, 1, 'Name cannot be left blank.'),
(753, 2, 'El nombre no puede dejarse en blanco.'),
(753, 3, 'Nom ne peut pas être laissée en blanc.'),
(754, 1, 'Forward your email to another email account.'),
(754, 2, 'Enviar su correo electrónico a otra cuenta de correo electrónico.'),
(754, 3, 'Veuillez faire parvenir votre courriel à un autre compte de messagerie.'),
(755, 1, 'Sends an automated reply to incoming messages.'),
(755, 2, 'Envía una respuesta automática a los mensajes entrantes.'),
(755, 3, 'Envoie un mail de réponse automatique aux messages entrants.'),
(756, 1, 'Select Theme'),
(756, 2, 'Seleccione Tema'),
(756, 3, 'Selectionnez Theme'),
(757, 1, 'Successfully Registered'),
(757, 2, 'registrado con éxito'),
(757, 3, 'Enregistré avec succès'),
(758, 1, 'to create an account.'),
(758, 2, 'para crear una cuenta.'),
(758, 3, 'pour créer un compte.'),
(759, 1, 'to Login.'),
(759, 2, 'para ingresar.'),
(759, 3, 'pour vous connecter.'),
(760, 1, 'Welcome'),
(760, 2, 'bienvenida'),
(760, 3, 'accueil'),
(761, 1, 'More'),
(761, 2, 'más'),
(761, 3, 'plus'),
(762, 1, 'Menu'),
(762, 2, 'menú'),
(762, 3, 'menu'),
(763, 1, 'Custom'),
(763, 2, 'costumbre'),
(763, 3, 'coutume'),
(764, 1, 'New'),
(764, 2, 'nuevo'),
(764, 3, 'nouveau'),
(765, 1, 'Include quoted text'),
(765, 2, 'Incluye texto de la cita'),
(765, 3, 'Inclure le texte cité'),
(766, 1, 'This file is 0 bytes, so it will not be attached.'),
(766, 2, 'Este archivo es de 0 bytes, por lo que no se adjunta.'),
(766, 3, 'Ce fichier est de 0 octets, de sorte qu\'il ne sera pas attaché.'),
(767, 1, 'This file exceeds the maximum attachment size, so it will not be attached.'),
(767, 2, 'Este archivo supera el tamaño máximo de datos adjuntos, por lo que no se adjunta.'),
(767, 3, 'Ce fichier dépasse la taille maximale des pièces jointes, de sorte qu\'il ne sera pas attaché.'),
(768, 1, 'Your mail has been sent successfully.'),
(768, 2, 'Su mensaje ha sido enviado con éxito.'),
(768, 3, 'Votre message a été envoyé avec succès.');
");
mysql_query("TRUNCATE TABLE `".$db_tableprefix."nesote_email_time_zone`");
mysql_query("INSERT INTO `".$db_tableprefix."nesote_email_time_zone` (`name`, `value`) VALUES
('Eniwetok, Kwajalein', '-12:00'),
('Midway Island', '-11:00'),
('Hawaii', '-10:00'),
('Alaska', '-09:00'),
('Pacific Time (US & Canada)', '-08:00'),
('Mountain Time (US & Canada)', '-07:00'),
('Central Time (US & Canada), Mexico City', '-06:00'),
('Eastern Time (US & Canada), Bogota, Lima', '-05:00'),
('Atlantic Time (Canada),Caracas, La Paz', '-04:00'),
('Newfoundland', '-03:30'),
('Brazil, Buenos Aires,Georgetown', '-03:00'),
('Mid-Atlantic', '-02:00'),
('Azores, Cape Verde Islands', '-01:00'),
('Western Europe Time, London, Lisbon, Casablanca', '+00:00'),
('Brussels, Copenhagen, Madrid, Paris', '+01:00'),
('Kaliningrad, South Africa', '+02:00'),
('Baghdad, Riyadh, Moscow, St.Petersburg', '+03:00'),
('Tehran', '+03:30'),
('Abu Dhabi, Muscat, Baku, Tbilisi', '+04:00'),
('Kabul', '+04:30'),
('Ekaterinburg, Islamabad, Karachi, Tashkent', '+05:00'),
('Bombay, Calcutta, Madras, New Delhi', '+05:30'),
('Kathmandu', '+05:45'),
('Almaty, Dhaka, Colombo', '+06:00'),
('Bangkok, Hanoi, Jakarta', '+07:00'),
('Beijing, Perth, Singapore, Hong Kong', '+08:00'),
('Tokyo, Seoul, Osaka, Sapporo, Yakutsk', '+09:00'),
('Adelaide, Darwin', '+09:30'),
('Eastern Australia, Guam, Vladivostok', '+10:00'),
('Magadan, Solomon Islands, New Caledonia', '+11:00'),
('Auckland, Wellington, Fiji, Kamchatka', '+12:00');

");

///Chat Start//////
mysql_query("TRUNCATE TABLE `".$db_tableprefix."nesote_chat_settings`");
mysql_query("INSERT INTO `".$db_tableprefix."nesote_chat_settings` (`name`, `value`) VALUES
('deafault_chatwindow_size', '3'),
('default_chat_sound', '1'),
('chat_history', '1'),
('chat_sound_file', 'chimes.mp3'),
('sound_format', 'mp3'),
('picture_format', 'jpeg, jpg, png, gif'),
('chat_smiley', '1'),
('chat_enable', '1');

");
mysql_query("TRUNCATE TABLE `".$db_tableprefix."nesote_chatwindow_settings`");
mysql_query("INSERT INTO `".$db_tableprefix."nesote_chatwindow_settings` (`name`, `width`, `height`) VALUES
('Tiny', 148, 50),
('Small', 148, 100),
('Normal', 148, 150),
('Large', 148, 400);

");
/////Chat End/////
mysql_query("TRUNCATE TABLE `".$db_tableprefix."nesote_email_shortcuts`");
mysql_query("INSERT INTO `".$db_tableprefix."nesote_email_shortcuts` (`keyvalue`, `description`) VALUES
('<strong>INS(Insert)+c</strong>', 'Compose'),
('<strong>INS(Insert)+r</strong>', 'Reply'),
('<strong>INS(Insert)+a</strong>', 'Reply All'),
('<strong>INS(Insert)+f</strong>', 'Forward'),
('<strong>INS(Insert)+q</strong>', 'Get Mail'),
('<strong>INS(Insert)+Space</strong>', 'Search'),
('<strong>INS(Insert)+h</strong>', 'Add New Folder'),
('<strong>INS(Insert)+w</strong>', 'Delete Folder'),
('<strong>INS(Insert)+d</strong>', 'Delete'),
('<strong>INS (Insert)+z</strong>', 'Send a Mail'),
('<strong>INS (Insert)+s</strong>', 'Save to Draft'),
('<strong>INS (Insert)+Esc</strong>', 'Discard a Mail'),
('<strong>INS(Insert)+p</strong>', 'Print a Mail'),
('<strong>Alt+r</strong>', 'Read'),
('<strong>Alt+u</strong>', 'Unread'),
('<strong>Alt+x</strong>', 'Star'),
('<strong>Alt+q</strong>', 'Unstar'),
('<strong>INS(Insert)+u</strong>', 'More Function'),
('<strong>INS(Insert)+v</strong>', 'Move to Function'),
('<strong>INS(Insert)+l</strong>', 'Empty Spam'),
('<strong>INS(Insert)+m</strong>', 'Empty Trash'),
('<strong>Alt+y</strong>', 'Select All'),
('<strong>Alt+z</strong>', 'Deselect All'),
('<strong>INS(Insert)+g</strong>', 'Add Contactgroup'),
('<strong>INS(Insert)+o</strong>', 'Delete Contact Group'),
('<strong>INS(Insert)+n</strong>', 'Add Contact Details'),
('<strong>Alt+m</strong>', 'Go to Mail Section'),
('<strong>Alt+c</strong>', 'Contact Section'),
('<strong>Alt+w</strong>', 'Go to Settings Sections'),
('<strong>INS(Insert)+t</strong>', 'Show Theme'),
('<strong>INS(Insert)+j</strong>', 'View Calendar'),
('<strong>INS(Insert)+k</strong>', 'To-do List'),
('<strong>INS(Insert)+y</strong>', 'Invite a Chat'),
('<strong>INS(Insert)+x</strong>', 'Logout');
");	
mysql_query("TRUNCATE TABLE `".$db_tableprefix."nesote_email_calendar_settings`");	
mysql_query("INSERT INTO `".$db_tableprefix."nesote_email_calendar_settings` (`name`, `value`) VALUES
('email_remainder', 1),
('view_event',0),
('calendar', 1);
");
?>